source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.MSBuildTargets/Readme.txt
source/VisualStudio.MSBuildTargets/VisualStudio.MSBuildTargets.nuproj
source/nanoFramework.Tools.VisualStudio.sln

- the current version of Nugeter can't handle our requirements (distributing stuff in build directory)
- reverting to a VS2015 project with Nugeter

Remove Nuget project from VS extension solution

---

source/VisualStudio.BuildTask/Extensions/CommandLineBuilderExtensions.cs
source/VisualStudio.BuildTask/MetaDataProcessorTask.cs
source/VisualStudio.BuildTask/Properties/AssemblyInfo.cs
source/VisualStudio.BuildTask/ResolveRuntimeDependenciesTask.cs
source/VisualStudio.BuildTask/VisualStudio.BuildTask.csproj
source/VisualStudio.BuildTask/nanoFrameworkBuild.targets
source/VisualStudio.Extension/BuildSystem/DeployedBuildSystem/nanoFramework.Tools.MSBuildTargets.props
source/VisualStudio.Extension/BuildSystem/DeployedBuildSystem/nanoFramework.Tools.MSBuildTargets.targets
source/VisualStudio.MSBuildTargets/VisualStudio.MSBuildTargets.nuproj
source/VisualStudio.MSBuildTargets/VisualStudio.MSBuildTargets.sln

- had to implement these in VS2015 solution to make it easier to build the Nuget package (in the future, all this should be moved to VS 2017)
- update Nuget package to include the supporting MSBuild tasks, project targets and suport tools

Add VS2015 solution for MSBuild tasks

---

source/Tools.Parser/Support.cpp

- origin string must be a single word otherwise VS isn't able to process the output

Correct error output for MetaDataProcessor

---

source/Tools.MetaDataProcessor/Info_Win32.cpp
source/Tools.MetaDataProcessor/MetaDataProcessor.cpp

- include headers now has correct case in file name (relevant for systems where file name case matters)
- bumped version to 1.0.10

Improvements in MetaDataProcessor

---

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate
source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate
source/Tools.BuildTasks/Nuget.MSBuildSystem/Nuget.MSBuildSystem.nuproj
source/Tools.MetaDataProcessor/MetaDataProcessor.cpp
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/source.extension.vsixmanifest

- fix #62
- bumped MSBuild system Nuget version to preview0033
- bumped VS extension to 0.1.16

Remove wrong code in MetaDataProcessor

---

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate
source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate
source/Tools.BuildTasks/MetaDataProcessorTask.cs
source/Tools.BuildTasks/Nuget.MSBuildSystem/Nuget.MSBuildSystem.nuproj
source/Tools.MetaDataProcessor/Info_Win32.cpp
source/Tools.MetaDataProcessor/MetaDataProcessor.cpp
source/VisualStudio.Extension/BuildSystem/DeployedBuildSystem/nanoFramework.Tools.MSBuildSystem.targets
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/source.extension.vsixmanifest

- Add code to generate skeleton code without requiring Interop support
- Add support options to MetaDataProcessor, Task and targets
- Bumped MSBuild System version to preview0037
- fixes #70
- update nf-interpreter submodule

Add function to generate skeleton code without Interop

---

source/Tools.MetaDataProcessor/MetaDataProcessor.vcxproj

- were different on build flavor which was causing issues when building in Debug

Correct AdditionalDependencies for Metadataprocessor

---

source/CSharp.AssemblyInfoTemplate/CSharp.AssemblyInfoTemplate.csproj
source/CSharp.AssemblyInfoTemplate/packages.config
source/CSharp.BlankApplication/CSharp.BlankApplication.csproj
source/CSharp.BlankApplication/packages.config
source/CSharp.ClassLibrary/CSharp.ClassLibrary.csproj
source/CSharp.ClassLibrary/packages.config
source/CSharp.ClassTemplate/CSharp.ClassTemplate.csproj
source/CSharp.ClassTemplate/packages.config
source/Tools.BuildTasks/Tools.BuildTasks.csproj
source/Tools.BuildTasks/packages.config
source/VisualStudio.Extension/Properties/AssemblyInfo.cs
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/VsPackage.cs
source/VisualStudio.Extension/packages.config
source/VisualStudio.Extension/source.extension.vsixmanifest

- this is preparation to add toolwindows
- need to add the package to ALL VSSDK related project no matter if they reference it or not
(explanation provided by Microsoft Extensibility team member)

Add Microsoft.VSSDK.BuildTools package

---

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml
source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs

- wrapped calls interacting with the device in try/catch blocks
- wrapped calls affecting the UI in dispacther
- add comments to documentat command handlers
- command handlers are responsible for disable/enable the respective buttons
- reorganized code in regions
-

Stability improvements

---

appveyor.yml
source/VisualStudio.Extension/Deployment/DeployProvider.cs
source/VisualStudio.Extension/ProjectSystem/ProjectProperties.cs
source/VisualStudio.Extension/Properties/AssemblyInfo.cs
source/VisualStudio.Extension/Resources/ResourceStrings.Designer.cs
source/VisualStudio.Extension/Resources/ResourceStrings.resx
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher
source/VisualStudio.Extension/source.extension.vsixmanifest

- wasn't including the target to the deployment list
- correct retry policy declaration (and use) for checking if device is in initialization state
- remove everything related with checking deployed assemblies because we are always deploying everything
- update Debug library Nuget package
- update AppVeyor removing the Nuget artifacts and deployment
- bump VS extension version to 0.1.41

Fixed deployment

---

appveyor.yml
source/Tools.MetaDataProcessor/ManagedElementTypes_Win32.h
source/Tools.MetaDataProcessor/MetaDataProcessor.cpp
source/VisualStudio.Extension/Properties/AssemblyInfo.cs
source/VisualStudio.Extension/source.extension.vsixmanifest

- was wrongly using the C native types instead of the "mapped" ones from the CLR
- fixes #115
- bump MDP to v1.0.19
- bump VS extension to 0.1.47

Fixes issues with typed array generation

---

appveyor.yml
source/VisualStudio.Extension/Properties/AssemblyInfo.cs
source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/packages.config
source/VisualStudio.Extension/source.extension.vsixmanifest

- add "force" option to ConnectAsync call to allow it to force refreshing the device capabilities
- remove temporary workaround for AppVeyor access to Nuget
- bump VS extension to v0.1.48

Update debug library

---

appveyor.yml
source/VisualStudio.Extension/Deployment/DeployProvider.cs
source/VisualStudio.Extension/Properties/AssemblyInfo.cs
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/packages.config
source/VisualStudio.Extension/source.extension.vsixmanifest

- after successfull deployment nF device is now reboot so that the assemblies are loaded
- fixes #111
- bump VS extension to 0.1.49

Device is now reboot after deployment

---

source/VisualStudio.Extension/Deployment/DeployProvider.cs
source/VisualStudio.Extension/Properties/AssemblyInfo.cs
source/VisualStudio.Extension/source.extension.vsixmanifest

- improve deploy provider code to include referenced projects in the deployment blob
- fixes #119
- bump VS extension version to 0.1.50

Fix issue with referenced projects not being deployed

---

source/VisualStudio.Extension/Deployment/DeployProvider.cs
source/VisualStudio.Extension/source.extension.vsixmanifest

- In the Visual Studio output window the size of the individual assembly being deployed is shown
- The same for the total size is calculated and shown
- Fixes #124
- Bump version of VS Extension to 0.1.51
Signed-off-by: piwi1263 <piwi1263@gmail.com>

Display assembly sizes on deployment

---

appveyor.yml
source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets

Correct name in targets file

---

source/VisualStudio.Extension/ProjectSystem/ProjectProperties.cs
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/app.config
source/VisualStudio.Extension/packages.config

Revert NuGet packages of VSProjectSystem back to 15.0.x.
Updating to VSProjectSystem 15.3 caused the Deploy option to vanish. The cause for this is an apparent regression on their code. 
Issue reported [here](https://github.com/Microsoft/VSProjectSystem/issues/247)
Deploy option verified to show as expected.

Revert Nuget packages

---

appveyor.yml
source/VisualStudio.Extension/Properties/AssemblyInfo.cs
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/packages.config
source/VisualStudio.Extension/source.extension.vsixmanifest

Update NuGet packages of VSProjectSystem to 15.3.
Bump VS extension to 0.1.60.
Previous attempt failed because the System.Composition package was updated to 1.1.0. Remaining at 1.0.31 doesn't break the Deploy feature.
Deploy option shows as expected in project node. All the remaining features as working too.

Update NuGet packages

---

source/VisualStudio.Extension/Targets/NFProjectSystem.CSharp.targets

Remove inclusion of user proj file in targets file
- Fixes warning from MSBuild about duplicate inclusion of file.
- Fixes/Closes/Resolves nanoFramework/Home#225

Fix duplicate import of user proj file

---

source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/app.config
source/VisualStudio.Extension/packages.config

Revert NuGet package to a version that works with VS extension.
This DLL is on the list of the DLLs which are automatically excluded from a VSIX package.
The reason for that is because it's supposed to exist as part of the VS regular install.
Why is this relevant? If we compile the VS extension against a version higher then the one that exists on the target system it will fail when the VS extension is launched.
The alternative would be to manually add it to the vsix manifest.
As we are not taking any particular advantage from using the latest and greatest version, the safest approach is to use a version that is in the requirement list of another NuGet package. That would be Microsoft.VisualStudio.Composition.
- Deployed to VS experimental instance and confirmed to wrok.
Signed-off-by: …

Revert NuGet for System.Threading.Tasks.Dataflow to 4.5.25.0

---

appveyor.yml
source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
source/VisualStudio.Extension/Properties/AssemblyInfo.cs
source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/packages.config
source/VisualStudio.Extension/source.extension.vsixmanifest

- Improve workflow to handle detection/set of device in InitializedState required for deployment.
- CLR is now being reboot after deployment.
- Update Debugger package to 0.4.0-preview02.
- Minor typos corrected.
- Bump VS extension to v0.1.62.
Deployed test app in VS experimental instance bumping the version numbers and retrieved the target details seeing the version being updated. This without requiring USB or manual target reconnections. 

Improve deployment workflow

---

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
source/VisualStudio.Extension/Properties/AssemblyInfo.cs
source/VisualStudio.Extension/source.extension.vsixmanifest

- Reboot flag was using a Linq which was being evaluated too late providing wrong information
- Bump VS extension to V0.1.65.
- Fixes wrong evaluation of boot option in deployment provider.
- Deployment of managed app in VS experimental instance.

Fix reboot condition evaluation in DeployProvider

---

source/CSharp.BlankApplication/Program.cs
source/VisualStudio.Extension/CorDebug/CorDebug.cs
source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/packages.config

- Correct parameter in StartDebugging
- Rework AttachEngine to force connection only if required
- Assemblies are now loaded after device is in initialized state
- Update debugger library
- Update debugger submodule @acb29129
- Remove Thread.Sleep() workaround from application template
- Fixe issue with breakpoints set in initial lines of code never being hit
- Performing debug on VS experimental instance

Fix early breakpoint set

---

source/VisualStudio.Extension/MessageCentre/MessageCentre.cs
source/VisualStudio.Extension/NanoFrameworkPackage.cs
source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs

- User options are now persisted using the registry instead of the solution suo file
- Preference for OptionShowInternalErrors is not output to welcome message anymore
- Definitive fix for ShowInternalErrors button in Device Explorer
_ VS experimental instance

Fix user options management and persistence

---

source/VisualStudio.Extension/MessageCentre/MessageCentre.cs
source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs

- General and operation messages are now output to nanoFramework output pane instead of debug pane which is now used only for messages after starting a debug session
- Output to Debug pane only when a debug session is active, all other messages don't belong there.

Improve messages output

---

source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs
source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher
source/VisualStudio.Extension/packages.config
source/VisualStudio.Extension/source.extension.vsixmanifest

- Increase retry timeout for deploy provider and AttachToEngine
- Remove forced detach from engine in AttachToEngine
- DetachFromEngine doesn't call engine stop anymore
- Update debugger Nuget to 0.5.0-preview098
- Update debugger sub-moldule @ 8c2dee3ad
- Increase extension version in manifest

Improvements in debug start and  deploy provider

---

source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs
source/VisualStudio.Extension/CorDebug/DebugPortSupplier.cs
source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
source/VisualStudio.Extension/NanoFrameworkPackage.cs
source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher
source/VisualStudio.Extension/packages.config

- Improve sanity check of native assemblies in DeployProvider (doesn't require call to GetDeviceInfo() anymore)
- Clean-up CorDebugProcess from unused methods and fields
- Remove repeated calls to connect and attach methods in debug start sequence
- Improve OnProcessExit code
- StopDebugging on CorDebugProcess now forces reboot of target (required to solve memory leaks caused by forced execution end)
- Package OptionShowInternalErrors is now getting the value from a nullable backing field (getting it from the registry was throwing exception on VS shutdown)
- Improve code in DeviceExplorer view model with non async messaging tasks
- Rework DebugPortSuplier to update availale ports on debug launch (was locked to the first device available when the constructor was called)
- Clean up code in …

Improvements in deployment and debug start/stop

---

source/VisualStudio.Extension/Rules/NanoFrameworkPropertyPage.xaml
source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets
source/VisualStudio.Extension/Targets/NFProjectSystem.props

- Rename and invert several msbuild properties to make it's use intuitive (were being used negated which was confusing)
- Rework nF project properties page accordingly
- Rework nF project properties page to properly set the msbuild options to generate interop stubs
- Correct case name of label to match project name
The following project properties have changed their name which will cause unwanted results, such the project stubs not being generated:
- NFMDP_PE_SKIP  >>  NFMDP_GENERATE_PE
- NFMDP_DUMP_SKIP >> NFMDP_DUMP_FILES
- NFMDP_STUB_SKIP >> NFMDP_GENERATE_STUBS
- NFMDP_DAT_SKIP >> NFMDP_DAT_FILES
- NFMDP_XML_SKIP >> NFMDP_XML_FILES)
- Improves usability
- Fixes nanoFramework/Home#315

Rework stub generation handling

---

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
source/VisualStudio.Extension/source.extension.vsixmanifest

Collecting assemblies to deploy across the solution.
Unlike before, we don't have to reference each NuGet package in the main project any more in order to have it deployed to the hardware. If some referenced project (any nesting level deep) needs a NuGet or other assembly reference, it will be picked up now for deployment even if the main project does not explicitly reference it.
Note: It is still necessary to uncheck the "deploy" option in Visual Studio configuration manager for all but the main project. Otherwise, the whole deployment gets done once for each project set to be "deployed".
This change eases deployment of multi-project solutions where referenced assemblies such as NuGet packages are only directly needed in projects referenced directly or deeper nested indirectly from the …

Assemblies referenced in other than the main project get deployed

---

source/VisualStudio.Extension/DebugLauncher/NanoDebuggerLaunchProvider.cs
source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
source/VisualStudio.Extension/Utilities/ReferenceCrawler.cs
source/VisualStudio.Extension/VisualStudio.Extension.csproj

- The command line wasn't being properly build with nested referenced projects. Because the loaded assemblies path list was incomplete some assemblyes were missing causing the debugger engine to crash VS
- Create new class ReferenceCrawler. Moved relevant methods there to allow reuse from deploy and launch providers
- Fixes nanoFramework/Home#378

Fix issue with launch command line

---

source/Tools.BuildTasks/GenerateBinaryOutputTask.cs
source/Tools.BuildTasks/Tools.BuildTasks.csproj
source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets

- Remove code from DeployProvider.
- Update MDP.targets to accomodate this.
- Add new build task: GenerateBinaryOutputTask.
- The previous approach required that a valid target was present. Plus it was part of the deploy workflow which was a bit of a stretch and in violation of the separation of concerns principle (one could need the binary file without necessarily deploy anything to a connected target).

Binary output file is now processed in msbuild task

---

source/VisualStudio.Extension/CorDebug/CorDebugClass.cs
source/VisualStudio.Extension/CorDebug/CorDebugType.cs

- Add proper implementation for GetStaticFieldValue and GetParameterizedType.
(shamelessly grabbed from NETMF/netmf-interpreter#552 😀 thank you @martincalsyn 👏)
- Tidy code.
- Despite the existing code was working fine. No issues whatsoever with peeking `static`'s (value was visible in watch, immediate, mouse over, etc.) it's always nice to improve code.

Improvements in CorDebugType and CorDebugClass

---

source/VisualStudio.Extension/NanoFrameworkPackage.cs

- Checks Windows version when extension is loaded. In case it's running on a Windows machine earlier than Windows 10 outputs a warning message to the user. This can save some frustration when trying to use it on a wrong Windows version.

Add Windows version check on extension load

---

source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets

- Add new task to MDP targets.
- Required for Babel obfuscator to find referenced libraries.
- Building Blinky sample in experimental instance and checking that the referenced DLLs are present in the obj folder.

Add task to copy referenced DLLs to obj folder

---

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
source/VisualStudio.Extension/DeployProvider/DeploymentAssembly.cs
source/VisualStudio.Extension/DeployProvider/DeploymentAssemblyDistinctEquality.cs
source/VisualStudio.Extension/VisualStudio.Extension.csproj

- Add new class DeploymentAssembly.
- Improve code in DeployProvider to correctly filter distinct assemblies.
- The current implementation with Linq Distinct() was not filtering assemblies in different locations thus causing repeated items in the deployment blob.

Fix deployment issue with repeated assemblies

---

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs

- Remove reboot command from DeviceErase handler.
- The command to reboot the CLR is already executed as part of the EraseAsync() call. No need to repeat.

Remove reboot command from DeviceErase

---

source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets

- Fix copy of referenced assemblies marked with CopyLocal.
- This task was failing on projects that use "out-of-project" path for the output folder and referenced assemblies marked with CopyLocal.

Fix copy of referenced assemblies marked with CopyLocal

---

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs

- After adding the device watcher and rescan feature the devices collection was not being properly managed as every new arrival/rescan/reenable was adding more devices to the existing collection and adding a new event handler on top of the existing ones.
- Tested by adding and removing devices on Visual Studio Experimental Instance.
Signed-off-by: sjmneves <sergio.neves@eclo.solutions>

Fix bad handling of devices collection

---

source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs

- Improve attach to engine step.
- When the execution reach that point the target has been connected for ages. The existing approach was an heritage of the times where connecting to a target and keeping the connection was really hard. Right now a operation to update the debugger flags is all it takes to validate the connection and move forward. Calling ConnectAsync was a performance killer and completely useless.

Improve attach to engine step

---

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs

- Remove deployment workaround for ESP32.
- After the last improvements in erase memory and disabling the SmartConfig thread, the deployment on ESP32 devices does not require this anymore.
- Several deployments test in VS experimental instance.

Remove deployment workaround for ESP32

---

source/VisualStudio.Extension-2019/NanoFrameworkPackage.cs
source/VisualStudio.Extension/NanoFrameworkPackage.cs

- In case Windows version is below 10, the extension shows an error message and wont load it's internal components.
- The debugger library requires UWP USB API to communicate with devices. Only Windows 10 and above have those.
- Resolves nanoFramework/Home#479.

Add check for Windows version on extension load

---

source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs

- Add check for type resolution failure on debug start.
- When type resolution fails there is no error shown in VS but prevents the debug session from starting without any indication to the developer on what is the reason for that.

Add check for type resolution failure on debug start

---

source/VisualStudio.Extension-2019/Targets/NFProjectSystem.CSharp.targets
source/VisualStudio.Extension/Targets/NFProjectSystem.CSharp.targets

- Rename framework define symbol to `NANOFRAMEWORK_1_0`.
- This is to follow the pattern with all other .NET frameworks. (dropping the v letter)

Rename framework define symbol to NANOFRAMEWORK_1_0

---

source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj
source/VisualStudio.Extension-2019/packages.config
source/VisualStudio.Extension/DebugLauncher/NanoDebuggerLaunchProvider.cs
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher
source/VisualStudio.Extension/packages.config

- QueryDebugTargetsAsync now explicitely connects to target device before launching debugger.
- Update debugger NuGet to 1.3.0-preview.14.
- Update debugger sub-module @130a833e.
- Fixes issues with deployment after increasing baud rate on WP.
- VS experimental instance. Deployment on STM32F769I and ESP32-WROVER.

Fix deployment issues

---

source/VisualStudio.Extension/ProjectSystem/ProjectTreePropertiesProvider.cs

- Add `Order` attribute to `ProjectTreePropertiesProvider`.
- Expanded project icon wasn't showing on project tree, instead the default one.
- Reported on [VS Developer Community](https://developercommunity.visualstudio.com/content/problem/597813/icon-property-in-iprojecttreepropertiesprovider-is.html) and fix suggested in dotnet/project-system#5183 (thank you so much @drewnoakes and @davkean 👏 😃 ).
- Fixes dotnet/project-system#5183.
- Loading nF project in VS experimental instance.

Fix project icon not showing on VS project tree

---

source/VisualStudio.Extension-2019/version.json
source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
source/VisualStudio.Extension/version.json

- Add code to check if project being deployed is the startup project. If not returns immediately.
- Bump version to 1.2.4.
- On Solutions with multiple projects the deploy provider deploys all projects marked to deploy in the Configuration Manager. This is unnecessary because the reference crawler takes care of listing all the required assemblies. Plus it can add a serious amount of wasted time to start debugging when it's deploying unnecessary projects one after the other.

Deploy provider now only deploys startup project

---

source/Tools.BuildTasks-2019/Tools.BuildTasks.csproj
source/Tools.BuildTasks/MetaDataProcessorTask.cs
source/Tools.BuildTasks/Tools.BuildTasks.csproj
source/Tools.BuildTasks/Utilities/DebuggerHelper.cs
source/Tools.BuildTasks/packages.config
source/VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets
source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj
source/VisualStudio.Extension-2019/packages.config
source/VisualStudio.Extension-2019/version.json
source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/packages.config
source/VisualStudio.Extension/version.json
source/nanoFramework.Tools.VisualStudio-2019.sln
source/nanoFramework.Tools.VisualStudio.sln

- Replace MDP NuGet reference.
- Rework MetaDataProcessorTask to be a regular msbuild Task instead of a ToolTask.
- Rework MDP targets for project system.
- Minor cosmetic changes in BuildTasks debugger helper.
- Bump version to 1.3.0.
**⚠️ Interop stubs generation is not working yet ⚠️**

Replace metadata processor with managed version

---

source/VisualStudio.Extension-2019/Targets/NFProjectSystem.props
source/VisualStudio.Extension/Targets/NFProjectSystem.props

- Change targets option to prevent VS from auto generating binding redirects (within app.config).
- Binding redirects aren't supported in nF plus this was causing a lot of issues like deployment errors, version mismatches, etc.

nF project system targets don't generate  binding redirects anymore

---

source/Tools.BuildTasks/MetaDataProcessorTask.cs

- AssemblyDefinition is now disposed on task end.
- Need to dispose the AssemblyDefinition before leaving because Mono.Cecil assembly loading and resolution operations leave the assembly file locked in the AppDomain preventing it from being open on subsequent Tasks.
- Fixes nanoFramework/Home#553.

Fix file locking on MDP task

---

source/Tools.BuildTasks-2019/Tools.BuildTasks.csproj
source/Tools.BuildTasks/Tools.BuildTasks.csproj
source/Tools.BuildTasks/packages.config
source/VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets
source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj
source/VisualStudio.Extension-2019/packages.config
source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets
source/VisualStudio.Extension/VisualStudio.Extension.csproj
source/VisualStudio.Extension/packages.config

- Minor fixes in MDP targets file.
- Closes nanoframework/Home#554.

Update MDP to 2.21.1

---

source/VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml
source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml

- Fix assembly reference on network config dialog.
- Network configuration window was unusable.

Fix assembly reference on network config dialog

---

source/VisualStudio.Extension/Utilities/ReferenceCrawler.cs

Shared projects have no target path because they do produce an output.
The target path is null, and only one null value can be added to the dictionary. More than one shared projects will fail.
Allows a solution to have more than one shared project.
I created a solution with 3 shared projects and successfully deployed to a device.
Signed-off-by: manuelxmarquez

Fix deployment for solutions with with more than one shared project

---

source/VisualStudio.Extension-2019/version.json
source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs
source/VisualStudio.Extension/MessageCentre/MessageCentre.cs
source/VisualStudio.Extension/version.json

- Remove call to update assemblies, now occurs at the correct step.
- Remove duplicate end of line when outputting message to output console.
- Bump version to 2019.2.0 and 2017.2.0.
- Follows nanoframework/nf-interpreter#1624.
- [#] Improvement (non-breaking change that improves a feature, code or algorithm)
- [#] Breaking change (fix or feature that would cause existing functionality to change)

Improve debug session start sequence

---

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs

- Remove output of `DeploymentException`.
- No need to output details about this expected exception that's used to signal VS of a deployment error.

Remove output of deployment exception

---

source/Tools.BuildTasks/ProcessResourceFiles.cs

Adds support for Bitmap type in resources and fixes namespace for fonts
- Resolves nanoFramework/Home#120
- Resolves nanoFramework/Home#121
Tested under debug VS extension
Signed-off-by: adriansoundy <adriansoundy@gmail.com>

Add resource support for Bitmaps and correct Font namespace

---

source/VisualStudio.Extension-2019/NanoFrameworkPackage.cs
source/VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml
source/VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
source/VisualStudio.Extension-2019/version.json
source/VisualStudio.Extension/NanoDeviceCommService/NanoDeviceCommService.cs
source/VisualStudio.Extension/NanoFrameworkPackage.cs
source/VisualStudio.Extension/ToolWindow.DeviceExplorer/SettingsDialog.xaml
source/VisualStudio.Extension/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
source/VisualStudio.Extension/version.json

- Add text box to enter list of ports to exclude from search.
- Add support for new property to retrieve/store this property in user preferences.
- Closes nanoFramework/Home#635.

Add support for COM Port black list in Device Explorer

---

Tools.BuildTasks/MetaDataProcessorTask.cs
VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets
VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets

- Add output variable to MDP task to output native assembly checksum.
- Add code to MDP targets file to set Azure Pipeline variable with native assembly checksum.
- This is now exposed as a build variable making it easier to be used in the pipeline.
- Experimental instance.

Expose native assembly checksum in Azure Pipelines

---

VisualStudio.Extension-2019/Targets/NFProjectSystem.targets
VisualStudio.Extension/Targets/NFProjectSystem.targets

- Remove this from project capabilites.
- Fixes nanoFramework/Home#712.
- Tested with VS 16.10 preview.

Remove advertising of PackageReferences

---

Tools.BuildTasks/ProcessResourceFiles.cs

- Copy Bitmaps before accessing their data, otherwise exceptions are thrown.
- Fixes nanoFramework/Home#702.
- Test project with resource file and adding the two "offending" formats.
After the fix the build completes succesfully:
```
Rebuild started...
1>------ Rebuild All started: Project: NFApp4-Resx, Configuration: Debug Any CPU ------
1>NFApp4-Resx -> C:\Users\JoséSimões\source\repos\NFApp4-Resx\NFApp4-Resx\bin\Debug\NFApp4_Resx.exe
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

Fix exceptions when processing image resource files

---

VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets
VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets

- Update MDP targets file to allow output dir to be freely set.
- Was wrongly forcing the output directory to be inside the project folder.

Fix output dir in MDP targets file

---

VisualStudio.Extension/CorDebug/CorDebugAppDomain.cs
VisualStudio.Extension/CorDebug/CorDebugProcess.cs
VisualStudio.Extension/CorDebug/MetaDataImport.cs

- Add check for debug symbols existing so the assembly and module loading only occur if those are available.
- Add missing assert from not implemented call.
- This would happen when an assembly is loaded with reflection using `Assembly.Load()`. Without this check the debugger would try to load the assembly and the respective module. That would fail miserably because the debug symbols are not available and we don't have any way to find out that. The call to `GetAssemblyFromScope()` is not implemented on purpose because we are allowing only one assembly for each MetadataImport.
- Resolves nanoFramework/Home#732.

Fix loading of assembly without debug symbols

---

VisualStudio.Extension/CorDebug/CorDebugProcess.cs

- Add thread sleep after device reboot to allow communication flow and device changing state.
- Update debugger sub-module @ 8e59558.
- Improves debug start on ESP32 device.

Fix debug start

---

VisualStudio.Extension/CorDebug/CorDebugProcess.cs
VisualStudio.Extension/DebugLauncher/NanoDebuggerLaunchProvider.cs
VisualStudio.Extension/NanoDeviceCommService/NanoDeviceCommService.cs

- Rework AttachToEngine to simplify workflow.
- Rework EnsureProcessIsInInitializedState to remove unnecessary reboot call and rename vars for consistency.
- Remove unnecessary debug engine creation in comm service.
- Remove unnecessary timeout setting in debug lunch provider.
- Update debugger sub-module @ 8e59558.
- Improves device detection.
- Fixes random issues with debug session start.

Improvements in debug session start

---

VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs
VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs
VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs

- Improve handler to allow enough time for collection to be populated and then perform the selection of the item.
- Fixes issue with a single device not being automatically selected when the devices collection changes.

Fix error with auto selection of device

---

VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets
VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets

- LoadHints aren't required anymore in nfproj files. 
- Bump versions to 2017.7.0 and 2019.7.0.
Note: it's OK to keep having NFMDP_PE_LoadHints in nfproj, but those won't be used anymore from now on.
- msbuild is perfectly capable to determine paths to all referenced assemblies.

Improvement in LoadHints for MDP targets

---

Tools.BuildTasks-2017/ProcessResourceFiles.cs

- Binary resources do not default to Bitmap anymore.
- With the current approach all binary resources where first attempted to be parsed as Bitmap which, on success, would prevent the resource from being added as a simple binary resource. This defeats the intent of adding a file as binary resource even if it's a bitmap. Typical use case is to store bitmap files to use it's binary data without requiring to reference the UI nuget.
- VS experimental instance: adding a bitmap file without extension which was successfully added as a binary resource.

Fix generator for binary resources

---

azure-pipelines.yml

- Improve pipeline to build VS2019 and VS2022 in separate jobs.
- Need to be able to build one or the other version.

Improve pipeline to build VS2019 and VS2022 in separate jobs

---

VisualStudio.Extension-2019/NanoFrameworkPackage.cs
VisualStudio.Extension-2019/NanoFrameworkPackage.vsct
VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj
VisualStudio.Extension-2019/app.config
VisualStudio.Extension-2019/packages.lock.json
VisualStudio.Extension-2019/version.json
VisualStudio.Extension-2022/NanoFrameworkPackage.cs
VisualStudio.Extension-2022/NanoFrameworkPackage.vsct
VisualStudio.Extension-2022/version.json
azure-pipelines.yml
vs-extension.shared/ToolWindow.DeviceExplorer/DeviceExplorer.cs
vs-extension.shared/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs

- Device Explorer commands are now fully async.
- Rework package init code to solve performance issues with loading.
- Remove unnecessary check for running on Win10.
- Fix package ref in VS2019.
- Fix app.config for VS2019.
- Fix code style on some files.
- Improves performance issues with loading.

Fix start-up issue with Device Explorer Tool Window

---

VisualStudio.Extension-2019/NanoFrameworkPackage.vsct
VisualStudio.Extension-2022/NanoFrameworkPackage.vsct
vs-extension.shared/ToolWindow.DeviceExplorer/DeviceExplorer.cs
vs-extension.shared/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs

- On device watcher disabling a message box is now shown.
- Improve button tooltip.
- Change Device Explorer window caption for consistency.
- Remove usings and tidy up code style on DeviceExplorerCommand.
- Improve feedback on device watchers state because current state feedback in toolbar icon and message on output pane may not be clear/visible enough. Especially for new comers.

Improve feedback on device watchers state

---

VisualStudio.Extension-2019/NanoFrameworkMoniker.cs
VisualStudio.Extension-2019/NanoFrameworkMoniker.imagemanifest
VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml
VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj
VisualStudio.Extension-2019/version.json
VisualStudio.Extension-2022/NanoFrameworkMoniker.cs
VisualStudio.Extension-2022/NanoFrameworkMoniker.imagemanifest
VisualStudio.Extension-2022/NanoFrameworkPackage.cs
VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml
VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj
VisualStudio.Extension-2022/version.json
vs-extension.shared/ProjectSystem/ProjectTreePropertiesProvider.cs
vs-extension.shared/ToolWindow.DeviceExplorer/DeviceExplorer.cs
vs-extension.shared/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
vs-extension.shared/vs-extension.shared.projitems

- Rework declaration of package GUID for VS2022.
- Move NanoFrameworkMonikers to each extension project (because of compilation).
- Rename for consistency.
- Update code and xaml controls accordingly.
- Fix guid in imagemanifest.
- Bump versions.
- Another stab on fixing the missing icons in VS2022.

Fix icon resources

---

VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs
VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs

- Add null check before accessing the property.
- Fixes potential issue in transitory situations where there could be no device.

Now checking for null ref before trying to select device

---

vs-extension.shared/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
vs-extension.shared/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs

- Add code to store/update connection source of a device.
- Improve code that outputs dev caps.
- Output of dev caps wasn't working on subsequent clicks after the 1st one.

Fix issue with device capabilities output after 1st output

---

VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml
VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml
vs-extension.shared/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs

- Add new property to view model exposing this capability.
- Bind MAC address field in network config dialog to this.
- MAC address is now editable only when the target allows it.

MAC address field editability fixed

---

VisualStudio.Extension-2019/IPMaskedTextBox/IPMaskedTextBox.xaml.cs
VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs
VisualStudio.Extension-2022/IPMaskedTextBox/IPMaskedTextBox.xaml.cs
VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs

- Empty IP address are now 0.0.0.0 and default mask is 255.255.255.0.
- The defaults were wrongly using IPAddress.Empty which is 255.255.255.255.

Fix default values for Network Dialog

---

CSharp.AssemblyInfoTemplate/CSharp.AssemblyInfoTemplate.vstemplate
CSharp.BlankApplication/CS.BlankApplication-vs2019.vstemplate
CSharp.BlankApplication/CS.BlankApplication-vs2022.vstemplate
CSharp.ClassLibrary/CS.ClassLibrary-vs2019.vstemplate
CSharp.ClassLibrary/CS.ClassLibrary-vs2022.vstemplate
CSharp.ClassTemplate/CSharp.ClassTemplate.vstemplate
CSharp.ResourceTemplate/CSharp.ResourceTemplate.vstemplate

- Category name was missing .NET.
- Fix lack of consistency on templates storage.

Fix category name of templates

---

VisualStudio.Extension-2022/Rules/general.xaml
VisualStudio.Extension-2022/Targets/NFProjectSystem.CSharp.targets

- Add CommandLineArgsForDesignTimeEvaluation property to targets and rule file.
- Fixes nanoframework/Home#1125.
- Required to fix blocking issue loading nfproj after release of VS 17.3.
- Following dotnet/roslyn#60855.
- Fix for reported issue in [Developer Community](https://developercommunity.visualstudio.com/t/NET-nanoFramework-extension-broken-on-1/10116629)
- Locally build in VS experimental issue and mainstream one.

Add CommandLineArgsForDesignTimeEvaluation property to project system

---

Tools.BuildTasks-2019/ProcessResourceFiles.cs

Removed the check of Icon as a bitmap and reverted it to as a binary entry in the resource file/
Fixes a problem with the Icon resources
. Added resources of vaious file types and images and checked that an entry in the resource designer 
has the appropriate c# code generated

Only check for supported bitmaps, all other images types are entered as byte arrays

---

VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml
VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml

- Fix name of debugger assembly in XAML header.
- Fixes opening Network config dialog.
- Running VS experimental instance.

Fix loading of Network configuration dialog

---

VisualStudio.Extension-2019/NanoFrameworkPackage.cs
VisualStudio.Extension-2022/NanoFrameworkPackage.cs
vs-extension.shared/MessageCentre/MessageCentre.cs
vs-extension.shared/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
vs-extension.shared/VirtualDeviceService/IVirtualDeviceService.cs
vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs

- Move output message block to message centre.
- Simplified several init methods for services.
- Tidy up calls in async package constructor.

Improve async package init

---

vs-extension.shared/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs

- Now checks for existing network configurations.
- Shows message box with information about this and doesn't show it anymore.
- Prevents errors and unwanted behaviors when trying to open and update network configuration for devices that don't support it.

Improve showing Network Configuration dialog

---

VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml
VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/SettingsDialog.xaml
VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
vs-extension.shared/NanoDeviceCommService/NanoDeviceCommService.cs
vs-extension.shared/VirtualDeviceService/IVirtualDeviceService.cs
vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs

- Improve start/stop.
- Improve message when instance is already running.
- Device watchers are now started independent of virtual device preferences.
- Upon successful install of nanoclr the virtual device manager now performs a device rescan.
- Improve responsiveness of UI when executing long running operations with virtual device service.
- General improvements in code starting virtual instance.
- Fix regex showing CLR version updated.
- Remove duplicated or confusing messages being written to virtual device output pane.
- General improvements in virtual device following community feedback.

Improvements in virtual device management

---

VisualStudio.Extension-2019/NanoFrameworkPackage.cs
VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
VisualStudio.Extension-2022/NanoFrameworkPackage.cs
VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs

- Fix wrapping of async operations.
- Virtual device init now uses fire and forget on package load.

Improvements in UI responsiveness with virtual device operation

---

VisualStudio.Extension-2019/NanoFrameworkPackage.cs
VisualStudio.Extension-2022/NanoFrameworkPackage.cs
vs-extension.shared/DeployProvider/DeployProvider.cs
vs-extension.shared/VirtualDeviceService/IVirtualDeviceService.cs
vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs

- On shutdown event handlers are removed before killing the process.
- Process is not nulled anymore on VS shutdown.
- Add handlers for VS shutdown.
- Add code to check and restart virtual device on deployment.
- Other minor improvements in stop virtual device.
- Need more robust start & stop of virtual device.

Improve virtual device shutdown and restart

---

vs-extension.shared/DeployProvider/DeployProvider.cs
vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs

- Add option to wait for debugger to tool parameters.
- Restarting virtual device will be done only if the setting is ON.
- Add message with nanoclr version at start.
- Improves virtual device start/stop.

Improvements in starting virtual device

---

CSharp.TestApplication/NFUnitTest.nfproj

- Add back this as nano.runsettings should be usable again now.
- Improve user experience with running unit test projects.

Add back nano.runsettings to unit test project template

---

CSharp.TestApplication/NFUnitTest.nfproj

- Remove unnecessary targets from Unit Test template project.

Remove unnecessary targets from Unit Test template project

---

VisualStudio.Extension-2022/NanoFrameworkPackage.cs

- Remove CodeBase attributes.
- Despite the code base attributes fixes the missing icons issue, it causes problems loading other libraries in the extension.

Remove CodeBase attributes

---

VisualStudio.Extension-2019/NanoFrameworkPackage.cs
VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml
VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
VisualStudio.Extension-2022/NanoFrameworkPackage.cs
VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/SettingsDialog.xaml
VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj
vs-extension.shared/VirtualDeviceService/IVirtualDeviceService.cs
vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs

- Add interface in settings dialog box in device explorer.
- Rework start/stop of nanoclr process.
- Add support for loading a local nanoCLR instance. Usefull for debugging and other developement scenarios.
- Improve virtual device start and stop.

Add support for loading local nanoCLR instance in virtual device

---

VisualStudio.Extension-2019/NanoFrameworkPackage.cs
VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj
VisualStudio.Extension-2019/packages.lock.json
VisualStudio.Extension-2022/NanoFrameworkPackage.cs
VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj
VisualStudio.Extension-2022/packages.lock.json
vs-extension.shared/CorDebug/CorDebugProcess.cs
vs-extension.shared/DebugLauncher/NanoDebuggerLaunchProvider.cs
vs-extension.shared/NanoOptions/NanoOptionsPageDebugging.cs
vs-extension.shared/vs-extension.shared.projitems

- Add nanoFramework options.
- Expose these on VS package.
- Add code to debugger launch provider and CorDebug process to set execution condition including this flag.
- Update nanoFramework.Tools.Debugger.Net to v2.4.33.
- Update debugger sub-module @2a53448.
- Exposes and implements this new execution option.

Add support to show (and process) exception and stack trace as option

---

VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs
VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs

- Now adding terminator to PEM files, if it's not present.
- Fixes uploading CA root certificates in PEM format.

Fix CA root certificate upload

---

VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj
VisualStudio.Extension-2019/packages.lock.json

- Revert update on VS2019 refs.
- Issues with VS2019 loading assemblies.

Revert update on VS2019 refs

---

VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs

- Revert unintentional changes.
- Restore functioning of network config dialog box. This code was commented out during debug and unintentionally left that way and made it to production.

Fix Network Configuration dialog

---

vs-extension.shared/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs

- Passing correct GUID for device.

Fix device property being passed to update manager

---

Tools.BuildTasks-2019/GenerateBinaryOutputTask.cs

- Added FileSharing.Read to File.Open
I'm dogfooding the MSBuild task that verifies whether the native assemblies required by a nanoFramework project's results are supported by the devices the software is intended to be run on. The MSBuild task analyzes the project's assembly plus referenced assemblies as present in the @(ReferencePath) MSBuild variable. Included in the referenced assemblies are the ones from the NuGet packages, as located in the package's directory that is shared by all projects in a solution. The MSBuild task reads the *.pe versions (via File.Open ("assembly.pe", FileMode.Open, FileAccess.Read, FileShare.Read)) to get the assembly's checksum.
If a solution with a lot of projects is (re-)built, often the MSBuild task accesses the assembly of a NuGet package for one …

Allow shared access to .pe files on build

---

VisualStudio.Extension-2022/Properties/AssemblyInfo.cs
VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj
VisualStudio.Extension-2022/app.config

- Updated `AssemblyInfo.cs` to include versioning for debug builds.
- Added `app.config` for assembly binding redirects to support debugging extension.
- Modified `VisualStudio.Extension-vs2022.csproj` to prevent version info generation for local builds and conditionally include `app.config` for debugging.
- Fix debugging with VS2022 experimental instance. Following the fixes introduced in #854 to load icon images, debugging the extension wasn't possible anymore because VS loaded either the "real" DLL or the debugging version depending on what being called (deployment for example loads the "real" version). This was reported back to the developer community issue, and this is following guidance provided there.
- Debugging extension in experimental instance.

Fix debugging VS2022 extension
