nanoframework/nf-Visual-Studio-extension

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.BlankApplication/NFApp.csproj, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/source.extension.vsixmanifest, source/VisualStudio.MSBuildTargets/Readme.txt, source/VisualStudio.MSBuildTargets/VisualStudio.MSBuildTargets.nuproj, source/nanoFramework.Tools.VisualStudio.sln
=> Initial testing with props and targets from Nuget package

nf-interpreter/src/HAL/Include/nanoHAL.h, nf-interpreter/src/HAL/Include/nanoHAL_Power.h, nf-interpreter/src/HAL/Include/nanoHAL_Time.h, nf-interpreter/src/PAL/Include/nanoPAL.h, nf-interpreter/src/PAL/Include/nanoPAL_Time.h
- required for MetaDataProcessor
=> Wrap includes for target headers

.gitmodules
=> Add submodule for nanoFramework repo

CONTRIBUTORS.md, README.md, docs/README.md, docs/coding-guidelines/cs-coding-style.md, docs/coding-guidelines/cxx-coding-style.md, docs/project-documentation/contributing-workflow.md, docs/project-documentation/contributing.md, docs/project-documentation/labels.md, source/VisualStudio.MSBuildTargets_/VisualStudio.MSBuildTargets.nuproj
=> Overal improvements in repo/project documentation

source/Tools.Parser/Support.cpp
=> Improve error output for MetaDataProcessor

source/Tools.MetaDataProcessor/MetaDataProcessor.vcxproj, source/VisualStudio.MSBuildTargets/VisualStudio.MSBuildTargets.nuproj
=> Rename output of MetaDataProcessor

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/source.extension.vsixmanifest, source/VisualStudio.MSBuildTargets/VisualStudio.MSBuildTargets.nuproj
=> Bumped Nuget version to preview0015

source/CSharp.BlankApplication/NFApp.csproj, source/CSharp.ClassLibrary/NFClassLibrary.csproj, source/VisualStudio.Extension/BuildSystem/DeployedBuildSystem/nanoFramework.Tools.MSBuildSystem.targets
- moved  configs for not using standard reference from targets to proj template files
- add missing copuy of build artifact from intermediate directory to output
=> Several improvements in targets

source/CSharp.BlankApplication/NFApp.csproj, source/CSharp.ClassLibrary/NFClassLibrary.csproj, source/VisualStudio.Extension/BuildSystem/DeployedBuildSystem/nanoFramework.Tools.MSBuildSystem.props, source/VisualStudio.Extension/BuildSystem/DeployedBuildSystem/nanoFramework.Tools.MSBuildSystem.targets
- moved project properties to props file
- the same with a couple of those misplaced in the targets file
=> Improve MSBuild props file

source/Tools.BuildTasks/MetaDataProcessorTask.cs, source/Tools.MSBuildSystem/Tools.MSBuildSystem.nuproj
- remove debug output log messages
- bumped Nuget version to preview0020
=> Improvements in MetaDataProcessor task

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/source.extension.vsixmanifest
- add Nuget package with msbuild to project templates and to extension source
- update Nuget package for MSBuildSytem (replacing previous MSBuildTargets)
=> Add msbuild to project templates

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/Tools.MSBuildSystem/Tools.MSBuildSystem.nuproj, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/source.extension.vsixmanifest
- update MSBuildSystem to preview0021
- bumped own version to 0.1.12.0
=> Update Nuget versions

source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/CSharp.ClassLibrary/NFClassLibrary.csproj
- also clean up csproj file
- fixes #27
=> Add missing ref to mscorlib Nuget package

source/Tools.MSBuildSystem/Tools.MSBuildSystem.nuproj, source/VisualStudio.Extension/BuildSystem/DeployedBuildSystem/nanoFramework.Tools.MSBuildSystem.targets
- add missing condition
- bumped Nuget version to preview0022
- fixes #29
=> Correct source path

source/Tools.BuildTasks/Extensions/CommandLineBuilderExtensions.cs, source/Tools.BuildTasks/MetaDataProcessorTask.cs, source/Tools.BuildTasks/Properties/AssemblyInfo.cs
- improve code in extensions
- correct bug in AppendSwitchIfTrue: wasn't setting the requested switch value
- implement calls to all availabale switches
- correct calls to some switches that were using a wring extension
- correct asembly properties
=> Several improvements in MetaDataProcessor

source/Tools.BuildTasks/GenerateNanoResourceTask.cs, source/Tools.BuildTasks/Tools.BuildTasks.csproj
=> Initial work on GenerateNanoResourceTask

source/Tools.BuildTasks/MetaDataProcessorTask.cs, source/Tools.BuildTasks/Properties/AssemblyInfo.cs, source/Tools.MSBuildSystem/Tools.MSBuildSystem.nuproj, source/VisualStudio.Extension/BuildSystem/DeployedBuildSystem/nanoFramework.Tools.MSBuildSystem.props, source/VisualStudio.Extension/BuildSystem/DeployedBuildSystem/nanoFramework.Tools.MSBuildSystem.targets
- major improvements on targets to build core libraries
- optimisations on targerts
- comment debug help on MDP
- bumped Nuget package to preview0025
=> Further work on MSBuild System targets

source/Tools.MSBuildSystem/Tools.MSBuildSystem.nuproj
=> Bumped Nuget version to preview0026

source/Tools.MSBuildSystem/Tools.MSBuildSystem.nuproj
=> Bumped Nuget version to preview0027

source/Tools.BuildTasks/MetaDataProcessorTask.cs, source/Tools.BuildTasks/Properties/AssemblyInfo.cs, source/Tools.MSBuildSystem/Tools.MSBuildSystem.nuproj
- this is to help debugging command execution
- bump MDP version to 1.3.0
- bump Nuget package version to preview0028
=> Add property to MDP to output command line to Log

source/Tools.MetaDataProcessor/MetaDataProcessor.cpp, source/Tools.Parser/AssemblyParser.cpp, source/Tools.Parser/Linker.cpp
- add detailed information on failure
- add version output on launch
- rename fields for clarity sake
=> Improvements in MetaDataProcessor

source/Tools.MSBuildSystem/Tools.MSBuildSystem.nuproj, source/VisualStudio.Extension/BuildSystem/DeployedBuildSystem/nanoFramework.Tools.MSBuildSystem.targets
- moved code to group in sections
- correct some typos in property names
- tidy up code
=> Improvements in targets file

source/Tools.MSBuildSystem/Tools.MSBuildSystem.nuproj
=> Bumped nuget version to preview0029

source/Tools.MetaDataProcessor/Info_Win32.cpp
=> Correct implementation of to lower on project name

source/Tools.MSBuildSystem/Tools.MSBuildSystem.nuproj, source/Tools.MetaDataProcessor/MetaDataProcessor.cpp
- bumped Nuget version to preview0030
=> Bumped MDP version to 1.0.11

source/Tools.MSBuildSystem/Tools.MSBuildSystem.nuproj, source/VisualStudio.Extension/BuildSystem/DeployedBuildSystem/nanoFramework.Tools.MSBuildSystem.props, source/VisualStudio.Extension/BuildSystem/DeployedBuildSystem/nanoFramework.Tools.MSBuildSystem.targets
- this is to make more convinient seting this property in a project
- add default property to false
- bumped Nuget version to preview0031
=> Improve property to control MDP command line output

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/source.extension.vsixmanifest
- bumped extension version to 0.1.13
=> Update Nuget packages throughout the extension

docs/cla.md
=> Add CLA document

README.md, appveyor.yml
- add build status badge to front end readme
=> Add AppVeyor yaml

appveyor.yml
=> Correct Nuget API key

appveyor.yml
=> Update GitHub auth token

source/CSharp.AssemblyInfoTemplate/CSharp.AssemblyInfoTemplate.csproj, source/CSharp.BlankApplication/CSharp.BlankApplication.csproj, source/CSharp.ClassLibrary/CSharp.ClassLibrary.csproj, source/CSharp.ClassTemplate/CSharp.ClassTemplate.csproj, source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/app.config
=> Change required framework version to 4.6

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/Tools.BuildTasks/Nuget.MSBuildSystem/Nuget.MSBuildSystem.nuproj, source/Tools.MetaDataProcessor/Info_Win32.cpp, source/Tools.MetaDataProcessor/MetaDataProcessor.cpp, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/source.extension.vsixmanifest
- this is on skeleton generation to help developer find out that there is an issue with the field name
- bumped MSBuild System Nuget version to preview0034
=> Add validation for missing or wrong field names

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/Tools.BuildTasks/Nuget.MSBuildSystem/Nuget.MSBuildSystem.nuproj, source/Tools.MetaDataProcessor/Info_Win32.cpp, source/Tools.MetaDataProcessor/MetaDataProcessor.cpp, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/source.extension.vsixmanifest
- output warning on potentialy wrong or invalid property name
- bumped Nuget version to preview0035
=> Improve output by adding validation to field names

source/Tools.MetaDataProcessor/Info_Win32.cpp
=> Replace str with safe version

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/Tools.BuildTasks/MetaDataProcessorTask.cs, source/Tools.BuildTasks/Nuget.MSBuildSystem/Nuget.MSBuildSystem.nuproj, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/source.extension.vsixmanifest
- Bumped MSBuild System version to preview0038
=> Fixed default value for SkeletonWithoutInterop

source/Tools.Parser/Parser.vcxproj
Fixes #73
Signed-off-by: piwi1263 <piwi1263@gmail.com>
=> Included the NetFxDirs in the include path

appveyor.yml, source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/Tools.MetaDataProcessor/cor.h, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/app.config, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
- several related wiht VS
- also nanoFrameowrk core lib and build system
- bumped VS extension version to 0.1.16
- correct AppVeyor yaml to add artifact to GitHub release draft
=> Update Nuget packages

appveyor.yml
=> Update appveyor yaml to help correct issue with GitHub deplymnt

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorer.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerPackage.vsct, source/VisualStudio.Extension/VisualStudio.Extension.csproj
- skeleton only (WIP)
- also rename vsct to DeviceExplorerPackage for clarity sake
=> Add toolbar to Device Explorer

source/VisualStudio.Extension/VisualStudio.Extension.csproj
=> Icon was mising from VS package

source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/source.extension.vsixmanifest
=> Fix missing icon

.gitmodules
=> Add nanoFramework debugger submodule

source/VisualStudio.Extension/NanoFrameworkPackage.cs, source/VisualStudio.Extension/Targets/NFProjectSystem.CSharp.targets, source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets, source/VisualStudio.Extension/Targets/NFProjectSystem.targets, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerPackage.vsct, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
- update all toolversion to 15.0
- addd codebase and VSIX attribute to project file
- several improvements Deveice Explorer
+ add new VM property to hold previous device
+ cleanup view model model class
+ update VS Extension GUID
+ improve disconnect device logic
=> Work on VS extension

appveyor.yml, source/VisualStudio.Extension/VisualStudio.Extension.csproj
- bump version to 0.1.36
- enable VSIX package creation for Release config
=> Update AppVeyor script

source/VisualStudio.Extension/Extensions/IVsOutputWindowPaneExtensions.cs
=> Correct what is sent to output pane

source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/app.config, source/VisualStudio.Extension/packages.config
- the new package is pulling a Threading package that isn't available yet on current VS releases
- fix #100
=> Revert Nuget package for VS Shell

appveyor.yml, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/Rules/NanoFrameworkPropertyPage.xaml, source/VisualStudio.Extension/Rules/general.browseobject.xaml, source/VisualStudio.Extension/source.extension.vsixmanifest
- fix #104
- bump VS extension to 0.1.42
=> Correct XAML rule for project properties

source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
- fix INotifyPropertyChanged in device explorer
- update Nuget packages
- update nf-debuger submodule @9a81784
- bump VS extension to 0.1.45
=> Fix issue with device add/removal

source/VisualStudio.Extension/Deployment/DeployProvider.cs, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs, source/VisualStudio.Extension/source.extension.vsixmanifest
- rework management of device capabilites retrieval (fix #112)
- deployment failure now returns correct result (fix #110)
- bump VS extension version to 0.1.46
=> Fixes several issues

source/VisualStudio.Extension/Targets/NFProjectSystem.Default.props, source/VisualStudio.Extension/Targets/NFProjectSystem.props
- the import order was wrong becuase it was replacing properties set in the project file
- also add condition to prevent properties from being overwritten
=> Fixed props import order

source/Tools.MetaDataProcessor/Info_Win32.cpp, source/Tools.MetaDataProcessor/MetaDataProcessor.cpp
=> Improve feedback and output on wrong or bad class field declaration

appveyor.yml, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets, source/VisualStudio.Extension/source.extension.vsixmanifest
=> Correct output path for skeleton project

source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets
=> Add missing targets to copy files to output directory

appveyor.yml, source/Tools.MetaDataProcessor/MetaDataProcessor.cpp, source/Tools.Parser/Linker.cpp, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/source.extension.vsixmanifest
- bump MDP version to 1.0.21
- bump VS extension to 0.1.52
=> Correct token name in pdbx file

appveyor.yml, source/Tools.MetaDataProcessor/Info_Win32.cpp, source/Tools.MetaDataProcessor/MetaDataProcessor.cpp, source/VisualStudio.Extension/Properties/AssemblyInfo.cs
- addresses nanoframework/nf-Visual-Studio-extension#123
- bump MDP to 1.0.22
- bump VS extension to 1.54.0
=> Improve code to detect missing backing fields

source/VisualStudio.Extension/source.extension.vsixmanifest
=> Bumped extension version

appveyor.yml, source/VisualStudio.Extension/Deployment/DeployProvider.cs, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/source.extension.vsixmanifest
- fixes #134
- bump VS extension version to 0.1.55
=> Remove call to reboot device after deployment

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/Tools.MetaDataProcessor/MetaDataProcessor.cpp, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
- update submodule (@ef942c9)
- update Nuget refs
- update templates with latest CorLib version
- update CorLib with latest changes
- bump MDP to v1.0.24
- bump VS extension to 0.1.57
=> Updates from nf-interpreter

source/VisualStudio.Extension/Deployment/DeployProvider.cs, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/source.extension.vsixmanifest
Improve the deploy output to included assembly version.
Also rework the output string to accommodate the above.
- Improve feedback to the developer working with the extension.
=> Improve deployment output

source/VisualStudio.Extension/ProjectProperties.cs, source/VisualStudio.Extension/ProjectSystem/ProjectProperties.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/app.config, source/VisualStudio.Extension/packages.config
=> Update Nuget packages in VS extension

source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
=> Update NuGet for debugger lib

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest, source/nanoFramework.Tools.VisualStudio.sln
=> Update ref of Corlib NuGet package to 1.0.0-preview028

source/VisualStudio.Extension/Deployment/DeployProvider.cs
Correct the line outputting the assembly description which was wrongly formatted.
Verify output window of VS.
=> Fix deploy message

source/VisualStudio.Extension/Deployment/DeployProvider.cs
- assembly version was showing empty for app assembly
=> Fix deployment message

appveyor.yml, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
- update Debugger reference and submodule
- bump VS extension to 0.1.61
Deployment in VS experimental instance.
=> Update debugger NuGet and submodule

source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
- Update Debugger to v0.4.0-preview026
- Bump VS extension to 0.1.63
- Fixes issue with deployment failing to detect correct execution state from device.
Deploying test app in VS experimental instance.
=> Fix issue with deployment

appveyor.yml, source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest, source/nanoFramework.Tools.VisualStudio.sln
- Now is able to perform soft reset or just nanoCLR according to target condition.
- Update nf-debugger submodule to @f4042eaa (for development and local testing only)
- Bump VS extension to 0.1.64
- Update appveyor to publish VSIX package to MyGet
- Improves deployment.
- Test deploy managed app with VS experimental instance.
=> Improve deployment provider

appveyor.yml, source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/NanoFrameworkPackage.cs, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DesignDataService.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/IDataService.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/ViewModelLocator.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
- Add support for auto-connect and reconnect to nano device
- Improve implementation of PingDeviceCommandHandler
- Update nf-debugger submodule to @64058e4d
- Add missing copyright header message in several code files
- Update Debugger Nuget to 0.5.0-preview019
- Bump VS extension to v0.1.66
=> Add auto-connect and reconnect features

source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
- Rework DeviceExplorerCommand to have SerialDebugClient created in UI thread
- Replace background worker with Task to handle connection work
- Improvements in async calls throughout the DeviceExplorerViewModel
- Update Debugger lib to 0.5.0-preview020
- Update sub-module nf-debugger @dd3bcdb
- Bump VS extension to v0.1.67
- Resolves nanoFramework/Home#247
=> Work on stability

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/NanoDeviceCommService/INanoDeviceCommService.cs, source/VisualStudio.Extension/NanoDeviceCommService/NanoDeviceCommService.cs, source/VisualStudio.Extension/NanoDeviceCommService/SNanoDeviceCommService.cs, source/VisualStudio.Extension/NanoFrameworkPackage.cs, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest, source/nanoFramework.Tools.VisualStudio.sln
- Add `NanoDeviceCommService` VS service provider to hold debug client
- Update VS package to be async and load new service
- Complete rework on Device Explorer view model
- Major rework on Device Explorer menu command manager
- Improve auto-connect feature
- Improve reconnect after deployment feature
- Update debugger Nuget package to 0.5.0-preview023
- Update submodule nf-debug @ 30e20e99
- Bump VS extension to 0.1.68
=> Major rework on Device Explorer

source/VisualStudio.Extension/Extensions/TaskExtensions.cs, source/VisualStudio.Extension/NanoDeviceCommService/INanoDeviceCommService.cs, source/VisualStudio.Extension/NanoDeviceCommService/NanoDeviceCommService.cs, source/VisualStudio.Extension/NanoFrameworkPackage.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher, source/VisualStudio.Extension/packages.config
- Remove several unucessary calls to SwitchToMainThreadAsync
- Rework NanoDeviceCommService service provider by removing unecessary methods
- Rework assigning of NanoDeviceCommService to device explorer view model
- Rework DeviceExplorerViewModel
- Update submodule nf-debugger to @9304433
- Update Debugger component Nuget to 0.5.0-preview025
- Fixes issues with VS responsiveness 
- Fixes issues with wrong or missing Assembly listing
=> Stability improvements

appveyor.yml, source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/NanoFrameworkPackage.cs, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerPackage.vsct, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher, source/VisualStudio.Extension/source.extension.vsixmanifest
- Each operation now performs the connection/disconnection from the device
- Rework Device Explorer view model and command provider accordingly
- Bump VS extension to 0.1.69
=> Remove connect/disconnect button from Device Explorer

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/NanoDeviceCommService/NanoDeviceCommService.cs, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
- Fix several issues related with device selection
- Improvements in DeviceCommService provider
- Improvements in Device Explorer view model
- Improvements in Device Explorer UI
- Update submodule nf-debugger @ a38f7f79
- Update Debugger component to 0.5.0-preview030
- Bump VS extension to 0.1.70
- Addresses several issues with Device Explorer
=> Work on Device explorer

appveyor.yml, source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/source.extension.vsixmanifest
- Better reporting on unwanted situation: can't connect to target device, exception thrown during deployment, unexpected execptions, etc
- Add version information for executable (was being outputed only for referenced assemblies)
- Bump VS extension to 0.2.1
=> Improvements in deployment provider

appveyor.yml, source/VisualStudio.Extension/Properties/AssemblyInfo.cs, source/VisualStudio.Extension/source.extension.vsixmanifest
=> Correct VS extension manifest

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Rework deploy provider to properly check device initialization state.
- Remove need to check for device previously deployed assemblies as criteria to reboot CLR or soft reboot. Not required and doesn't make sense anymore.
- Requires nanoCLR v0.1.0-preview.371
- Fixes nanoFramework/Home#250
=> Rework deploy provider

GitVersion.yml, appveyor.yml, source/VisualStudio.Extension/source.extension.vsixmanifest
- Add GitVersion config file
- Update AppVeyor script
- Update vsix manifest to use tag for version
=> Implement semantic versioning with GitVersion

GitVersion.yml, appveyor.yml
=> Further tweak on semantic versioning

source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher, source/VisualStudio.Extension/packages.config
- Update Debugger Nuget to 0.5.0-preview056
- Fixes/Closes/Resolves nanoFramework/Home#253
=> Fix Console.WriteLine()

source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs
- On debug stop engine is not stopped anymore
- Clean up code
+semver:fix
- Fixes issue with starting debug sessions after the 1st
=> On debug stop engine is not stopped anymore

GitVersion.yml, appveyor.yml, source/VisualStudio.Extension/source.extension.vsixmanifest, update-vsix-manifest.ps1
=> Add PowerShell script to update version in VSIX manifest

GitVersion.yml
=> Update PS script to get proper VS extension version

GitVersion.yml, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, update-vsix-manifest.ps1
=> Update debugger library (improvements)

GitVersion.yml, appveyor.yml, source/VisualStudio.Extension/source.extension.vsixmanifest, update-vsix-manifest.ps1
=> Improvements in semantic version config

GitVersion.yml, source/CSharp.AssemblyInfoTemplate/CSharp.AssemblyInfoTemplate.vstemplate, source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/CSharp.ClassTemplate/CSharp.ClassTemplate.vstemplate
- Remove RequiredFrameworkVersion from project templates
- Update GitVersion configuration so that patch is not increased automaticaly
=> Remove RequiredFrameworkVersion from project templates

source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher, source/nanoFramework.Tools.VisualStudio.sln
=> Update nf-interpreter submodule @ 9a5d17ea

source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs, source/VisualStudio.Extension/MessageCentre/MessageCentre.cs
- Create private output window for nF
- Enable internal errors ON by default
- Improve checking on potential critial situation when the device reports no assembly
=> Improvements in output window

source/VisualStudio.Extension/MessageCentre/MessageCentre.cs
- Add timestamp to message output
- Replace String.Format
- Remove @ chars
- Fixes/Closes/Resolves nanoFramework/Home#259
=> Add timestamp to message output

source/VisualStudio.Extension/Targets/NFProjectSystem.CSharp.targets
- Enable shared projectes capability in nF project system
- Fixes/Closes/Resolves nanoFramework/Home#261
=> Add support for shared projects

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
- Update Nuget for debugger lib and Core Library (template)
- Update debugger submdule to @9c095cb9
=> Update debugger library

source/CSharp.AssemblyInfoTemplate/CSharp.AssemblyInfoTemplate.csproj, source/CSharp.AssemblyInfoTemplate/packages.config, source/CSharp.BlankApplication/CSharp.BlankApplication.csproj, source/CSharp.BlankApplication/packages.config, source/CSharp.ClassLibrary/CSharp.ClassLibrary.csproj, source/CSharp.ClassLibrary/packages.config, source/CSharp.ClassTemplate/CSharp.ClassTemplate.csproj, source/CSharp.ClassTemplate/packages.config, source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/Tools.BuildTasks/packages.config, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/app.config, source/VisualStudio.Extension/packages.config
- Update Nuget packages related with VS extensibility
-  Candidate to fix a couple of issue reporting VS instability
- Several deployments in VS experimental
=> Update Nuget VS packages

source/VisualStudio.Extension/CorDebug/CorDebugAppDomain.cs, source/VisualStudio.Extension/CorDebug/CorDebugAssembly.cs, source/VisualStudio.Extension/CorDebug/CorDebugBreakpoint.cs, source/VisualStudio.Extension/CorDebug/CorDebugBreakpointStepper.cs, source/VisualStudio.Extension/CorDebug/CorDebugChain.cs, source/VisualStudio.Extension/CorDebug/CorDebugClass.cs, source/VisualStudio.Extension/CorDebug/CorDebugCode.cs, source/VisualStudio.Extension/CorDebug/CorDebugEnum.cs, source/VisualStudio.Extension/CorDebug/CorDebugEval.cs, source/VisualStudio.Extension/CorDebug/CorDebugFrame.cs, source/VisualStudio.Extension/CorDebug/CorDebugFunction.cs, source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs, source/VisualStudio.Extension/CorDebug/CorDebugStepper.cs, source/VisualStudio.Extension/CorDebug/CorDebugThread.cs, source/VisualStudio.Extension/CorDebug/CorDebugValue.cs, source/VisualStudio.Extension/CorDebug/DebugPort.cs, source/VisualStudio.Extension/CorDebug/MetaDataImport.cs, source/VisualStudio.Extension/CorDebug/Pdbx.cs, source/VisualStudio.Extension/DebugLauncher/NanoDebuggerLaunchProvider.cs, source/VisualStudio.Extension/MessageCentre/MessageCentre.cs, source/VisualStudio.Extension/MessageCentre/MessageCentreBase.cs, source/VisualStudio.Extension/NanoFrameworkPackage.cs, source/VisualStudio.Extension/ProjectSystem/GlobalPropertiesProvider.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorer.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/Services/NanoFrameworkService/NFSerialDebugClientService.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher
- Fix issue with fields and properties not being evaluated during debug session
- Rename several vars and fields to follow coding style
- Remove unused using's
- Code clean-up
=> Fix several issues with debug session 

source/VisualStudio.Extension/CorDebug/CorDebugAssembly.cs
- Add networking sockets to list of official assemblies
=> Add networking sockets to list of official assemblies

source/Tools.MetaDataProcessor/MetaDataProcessor.cpp
=> Update nf-interpreter submodule @37152fa3

source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
- Update debugger to 0.5.0-preview064
- Resolves nanoFramework/Home#276
- Fix nanoFramework/Home#270
=> Update debugger to 0.5.0-preview064

source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs, source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher, source/VisualStudio.Extension/packages.config
- Update debugger lib
- Update code related with RebootOptions as required
=> Update debugger lib

source/Tools.MetaDataProcessor/MetaDataProcessor.cpp, source/Tools.MetaDataProcessor/Various.cpp
=> Update nf-interpreter submodule @13cb983f

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
- Fix network config button visibility
- Fixes issue with button ever being disabled
=> Fix network config button visibility

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Add code to deploy provider to find the referenced assemblies of the referenced projects and add those to the deployment
- Resolves nanoFramework/Home#302
=> Work on deployment provider

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
- Update Nuget version for template
=> Update Nuget version for template

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Add code to load individually each assembly in order to read the version
- Remove code that was trying to get the referenced assemblies from the referenced projects
=> Fix issue with deployed assemblies version missing

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs
- Add URLs to Device Explorer window
- Improving usability of Device Explorer 
- Give visibility to the documentation pages and Slack workspace
=> Add URLs to Device Explorer window

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
- Update debugger Nuget package to 0.5.0-preview.88.build.227
- Update debugger submdoule @ a15b4d88
- Update code to work with this new property
- Fix issue preventing showing network configuration dialog when there was no configuration on the device
=> Add support for automatic DNS addresses property

source/CSharp.ClassTemplate/CSharp.ClassTemplate.vstemplate
- Remove wrong reference to System in class template
- Fixes nanoFramework/Home#309
=> Remove wrong reference to System in class template

source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs, source/VisualStudio.Extension/DebugLauncher/NanoDebuggerLaunchProvider.cs, source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/NanoFrameworkPackage.cs, source/VisualStudio.Extension/ProjectSystem/ProjectProperties.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/app.config, source/VisualStudio.Extension/packages.config
- Rework several potential deadlocks with deploy provider and CorDebugProcess
- Update several Nuget packages
- Improves debug and deploy experience and prevents VS from freezing
=> Improvements in deploy provider and debugger engine

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Remove target reboot after deployment
- Fixes deployment issues and various issues with debug session starting
- Deploying and launching debugging session in VS experimental instance.
- Hit F5 and shortly after 🛑 button. 
- Launched 25 debug sessions 😅  in a row without a single failure or hiccup. 🚀 
=> Remove target reboot after deployment

source/VisualStudio.Extension/DebugLauncher/NanoDebuggerLaunchProvider.cs, source/VisualStudio.Extension/NanoFrameworkPackage.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/ViewModelLocator.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/app.config, source/VisualStudio.Extension/packages.config
- Major update of a bunch of Nugets 📦 
- Finally managed to update Microsoft.VisualStudio.Debugger.Engine 🎉 
- Update code and using's as required
=> Major update on Nugets 📦 

source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs
- Rework the code that is attaching the engine to the target debugger: the attachment is now always a forced connection to make sure the targets receives a Ping so the `Debugger_Enabled` flag is properly set.
- Minor code changes to follow coding guidelines
- Improvements in launching a debugger session
- Launching debugging session of Blinky sample app in VS experimental instance.
=> Improvements in debug engine initialization

source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
- Update debugger Nuget to 0.5.0-preview091
- Update debugger sub-module @ 8329b8f
- Fixes/Closes/Resolves nanoFramework/Home#332
=> Update Debuger package

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
=> Update refs and dependencies of mscorlib to 1.0.0-preview049

source/VisualStudio.Extension/NanoFrameworkPackage.cs
- Minor improvements in the welcome message sequence
=> Minor improvements in the welcome message sequence

source/Tools.MetaDataProcessor/Info_Win32.cpp, source/Tools.MetaDataProcessor/MetaDataProcessor.cpp, source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/DeployProvider/DeploymentException.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher, source/VisualStudio.Extension/packages.config
- Deployment provide now checks if the native assemblies required by the deployment blob are available in the target device, if not the deployment fails with a helpfull message
- Add new class DeploymentException
- General improvements in the exception handling and report in DeployAsync
- Update debug lib to 0.5.0-preview094
- Update sub-module @ 2a97ac94
- Closes nanoFramework/Home#329
=> Add check step for native assemblies on the device

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Add list of exception assemblies for deployment checking
- This is required in order to deal with assemblies that do not have native implementation and other exception situations
=> Add list of exception assemblies for deployment checking

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Fix for wrong outcome from assemblies check
=> Fix for wrong outcome from assemblies check

source/VisualStudio.Extension/MessageCentre/MessageCentre.cs
- Fix for random freeze in VS during debug start
=> Fix for random freeze in VS during debug start

source/VisualStudio.Extension/CorDebug/CorDebugBreakpointStepper.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
- Update Nuget package
- Udpdate sub-module @fd308896
=> Update debugger to 0.5.0-preview095

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
=> Update references of mscorlib to 1.0.0-preview050

source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs
=> Improvements in stopping a debugger session

source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs
=> Debug start sequence was missing a forced connect

source/Tools.MetaDataProcessor/Info_Win32.cpp, source/Tools.MetaDataProcessor/MetaDataProcessor.cpp
- Rework MDP to generate CMake module for assemblies (was generating a useless dotNetMF.proj)
- Add copyright and link to GitHub repo on MDP start message
- Fix version info missing when generating stubs for class libs
- Bump MDP version to 1.2.0
- Fixes issue with correct version inclusion on class libraries
- Closes nanoFramework/Home#170
=> Work on MDP

source/Tools.MetaDataProcessor/Info_Win32.cpp, source/Tools.MetaDataProcessor/MetaDataProcessor.cpp
- Fix several issues with CMake syntax in templates
- Improve customization message
- Change CMake module name to make it easy to interop modules to gitignore
- Bump MDP version to 1.3.0
- [ x] My code follows the code style of this project.
=> Various fixes for stubs generation

source/Tools.MetaDataProcessor/Info_Win32.cpp, source/Tools.MetaDataProcessor/MetaDataProcessor.cpp
- Fix CMake syntax in stubs template
- Fix missing CR
- Bump MDP to v1.4.0
=> Various fixes and improvements on MDP

source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs, source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/NanoDeviceCommService/NanoDeviceCommService.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher, source/VisualStudio.Extension/packages.config
- Add code to make sure DebugEngine exist on toolbar buttons and DeployProvider
- DetachFromEngine now also disconnects from device
- Update debugger Nuget to 0.5.0-preview105
- Update sub-module @ 1b904c99
- Fixes/Closes/Resolves nanoFramework/Home#346
=> Improvements in debug start/stop

source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets
- Fixes nanoFramework/Home#347
=> Add missing parameters to MDP Task

source/VisualStudio.Extension/Targets/NFProjectSystem.CSharp.targets
- Allows developer to add references to assemblies in the file system
=> Add removed capability to browse for assemblies

source/VisualStudio.Extension/NanoDeviceCommService/NanoDeviceCommService.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher, source/VisualStudio.Extension/packages.config
- Closes nanoFramework/Home#356
=> Work extension

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- The previous method loads the assembly and keeps a lock on the file thus preventing any furhter access to it, now it's loading it as a byte array into memory which doesn't have that side effect
- Fixes nanoFramework/Home#361
=> Change assembly loading method

source/CSharp.BlankApplication/Program.cs
- Adding console writeline shows a message illustrating the capability
- No need to "force" use of try-catch
- Adding a thread sleep infinite allows launching a debug session, without this a new comer sees the debug start and suddenly stop which could lead to think that something is wrong
=> Improve blank application template

source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/Tools.BuildTasks/packages.config, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/app.config, source/VisualStudio.Extension/packages.config
=> Update Nugets for VS extension

source/VisualStudio.Extension/Targets/NFProjectSystem.CSharp.targets, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml, source/VisualStudio.Extension/source.extension.vsixmanifest
- Defines compiler define to help developers identifying platform (in code reuse use cases, for example)
=> Add framework constant to project systems defines

source/VisualStudio.Extension/IPMaskedTextBox/IPMaskedTextBox.xaml.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs
- Fixed wrong setting of DNS on save network config
- Minor UI improvements
- Fixes nanoFramework/Home#373
=> Improve display of network config on DHCP

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
=> Update mscorlib Nuget ref to 1.0.0-preview062

source/VisualStudio.Extension/CorDebug/CorDebugAssembly.cs
- These recently added assemblies were missing from the framework class libraries list
=> Add new assemblies to framework assemblies list

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml
=> Replace Slack URL and mention with Discord

source/VisualStudio.Extension/NanoFrameworkPackage.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml
- Also replaced remaining link and mention to Slack
=> Improve Discord mention

source/Tools.MetaDataProcessor/MetaDataProcessor.cpp, source/Tools.MetaDataProcessor/MetaDataProcessor.vcxproj, source/Tools.MetaDataProcessor/MetaDataProcessor.vcxproj.filters, source/Tools.MetaDataProcessor/minheap.cpp, source/Tools.MetaDataProcessor/nanoHAL_Watchdog_stubs.cpp
- Update @167c4712
- Fix code in MDP as required
- Remove unused messaging port from HAL config
- Bump MDP version to v1.5.0
=> Update nf-interpreter sub-module

source/VisualStudio.Extension/Converters/AuthenticationTypeConverter.cs, source/VisualStudio.Extension/Converters/EncryptionTypeConverter.cs, source/VisualStudio.Extension/Converters/InterfaceTypeToBoolConverters.cs, source/VisualStudio.Extension/Converters/MacAddressConverter.cs, source/VisualStudio.Extension/Converters/NetworkInterfaceTypeConverter.cs, source/VisualStudio.Extension/Converters/RadioTypeConverter.cs, source/VisualStudio.Extension/ProjectSystem/GlobalPropertiesProvider.cs, source/VisualStudio.Extension/ProjectSystem/ProjectProperties.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, source/VisualStudio.Extension/Utilities/EnumToItemsSource.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
- update debugger Nuget to 0.5.0-preview120
- udpate submodule @8617bd96
- Add converters for mvvm properties
- Add utility to provide ItemsList from enum with items with description attribute
- Rework NetworkConfiguration code to use bindings to view modle instead of manual properties set/get
- Add converters for several properties
- Major rework on xaml and code behind
=> Work on network config dialog

source/VisualStudio.Extension/Rules/none.xaml
- This was causing an exception when right click on the project icon in Solution Explorer
=> Update none.xaml rule

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml
- Improve communication with users
=> Minor changes in device explorer wording

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml
-  Rework templating and styling of treeview
- Device items in treeview weren't following VS theme. Particularly noticeable when using dark theme.
=> Improve device explorer treeview

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml
- Improving this to increase the IP factor: once set the interface type shouldn't be changed. 
=> Network interface type is now read only

source/VisualStudio.Extension/Targets/NFProjectSystem.CSharp.targets
- Add property group to include compiler response file.
- Required to keep Roslyn happy when building mscorlib. 
=> Fix compiler warning on missing System.Object on mscorlib

source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/VisualStudio.Extension/NanoFrameworkPackage.cs, source/VisualStudio.Extension/ResXFileCodeGenerator/ResXFileCodeGenerator.cs, source/VisualStudio.Extension/Targets/NFProjectSystem.CSharp.targets, source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
- Add correct implementation of GenerateNanoResource Task
- Add customized implementation of resx file generator
- Update targets files to use new task
- nanoFramework project system was still missing support for managed resource files  
- Experimental instance
=> Add resx file generator

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- This file is a copy of the deployment area content
- Provides a binary format file ready to be used allowing the developer to grab it and flash the target device without requiring VS
- Closes nanoFramework/Home#255
=> Deploy provider now generates a binary file for standalone deployment

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Improves output of binary file name to make it clearer
=> Improve output of binary file name

source/Tools.BuildTasks/GenerateNanoResourceTask.cs, source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/NanoFrameworkPackage.cs, source/VisualStudio.Extension/ResXFileCodeGenerator/ResXFileCodeGenerator.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
- Remove own implementations of BaseCodeGenerator and BaseCodeGeneratorWithSite
- Add checks for not being in the UI thread
- Small improvements in GenerateCode()
- Fix missing renames to nanoresources
- Comment out font and bitmap resources because these aren't supported in native
- Update related Nuget packages
=> Improvements and fixes on ResXFileCodeGenerator

source/VisualStudio.Extension/NanoFrameworkPackage.cs, source/VisualStudio.Extension/ResXFileCodeGenerator/NFResXFileCodeGenerator.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
- Rework resx editor accordingly
- Rename ResXFileCodeGenerator to NFResXFileCodeGenerator
- Bump extension version to 0.6.0.0
- The latest and greatest versions available seem to broke the extension. Reverting to an older version in hope that this can solve those reported issues.
- Experimental instance of VS 15.8.4
=> Revert TextTemplate packages

source/VisualStudio.Extension/Targets/NFProjectSystem.props
- Should be consistent with the remaining props and target files
=> Fix tools version in props file

.github_changelog_generator, GitVersion.yml, appveyor.yml, generate-change-log.ps1, upload-vsix-myget.ps1
- Add configuration file
- Add PS script to generate change log on tags
- Update AppVeyor yaml to:
+ build on tags
+ deploy to MyGet only on tags
+ install ruby and github_changelog_generator on develop builds
- Update PS upload script:
+ to skip upload when this is not a tag
+ improve console output for a clearer build log
- Need to get the changelog working
=> Work on changelog generator for develop branch

appveyor.yml, generate-change-log.ps1
- Update github user configs in AppVeyor yaml
- Minor improvements in github release message
- Add missing git command to push commit with change log
- Fixes issue with committing the change log file back to the repo after update
=> Fix changelog generator

source/CSharp.AssemblyInfoTemplate/CSharp.AssemblyInfoTemplate.csproj, source/CSharp.AssemblyInfoTemplate/packages.config, source/CSharp.BlankApplication/CSharp.BlankApplication.csproj, source/CSharp.BlankApplication/packages.config, source/CSharp.ClassLibrary/CSharp.ClassLibrary.csproj, source/CSharp.ClassLibrary/packages.config, source/CSharp.ClassTemplate/CSharp.ClassTemplate.csproj, source/CSharp.ClassTemplate/packages.config, source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/Tools.BuildTasks/packages.config, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
- Several Nugets updated
- Remove dependency from Microsoft.VSSDK.BuildTools
=> Update dependency packages

source/Tools.MetaDataProcessor/MetaDataProcessor.cpp
- Makes it easier to maintain the version string at a single place.
=> Extract MDP strings to make it easy to maintain

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs
- Selection of interface type is now possible if there is no configuration stored in the device.
- Fixes nanoFramework/Home#420
=> Improve Network configuration dialog

source/VisualStudio.Extension/Targets/NFProjectSystem.CSharp.targets
- Required for MSTest vs compatibility
=> Adjust project capabilites

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml
=> Fix URLs in Device Explorer

GitVersion.yml, appveyor.yml, generate-change-log.ps1, upload-vsix-myget.ps1
- Also on Gitversion config
- Minor tweaks in log messages
=> Improvements on CI and CD scritps

appveyor.yml, commit-assemblyinfo-changes.ps1, generate-change-log.ps1
=> Improvements on CI & CD

source/Tools.MetaDataProcessor/Info_Win32.cpp
- Missing declaration of extern global for assembly
- Fix empty lines on headers and source files
=> Improve stubs skeletons

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
=> Update mscorlib NuGet to v1.0.4

azure-pipelines.yml, source/CSharp.AssemblyInfoTemplate/CSharp.AssemblyInfoTemplate.csproj, source/CSharp.AssemblyInfoTemplate/packages.config, source/CSharp.BlankApplication/CSharp.BlankApplication.csproj, source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.BlankApplication/packages.config, source/CSharp.ClassLibrary/CSharp.ClassLibrary.csproj, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/CSharp.ClassLibrary/packages.config, source/CSharp.ClassTemplate/CSharp.ClassTemplate.csproj, source/CSharp.ClassTemplate/packages.config, source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/Tools.BuildTasks/packages.config, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/app.config, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest, source/version.json
- Update templates with mscorlib 1.1.0.
- Update debugger NuGet to 1.0.1-preview-037.
- Bump version to 1.0.3.
=> Update several NuGets

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/Resources/ResourceStrings.Designer.cs, source/VisualStudio.Extension/Resources/ResourceStrings.resx
- Increase timeout to wait for device initialized.
- Target deployment area is now erased before deployment.
- Add reset to ESP32 before actual deployment.
- Add retry attempt for ESP32 devices on initial deployment failure.
- Improve deployment and debug session start experience.
=> Improve deployment experience

source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
=> Update referenced version of mscorlib in templates

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Fix deployment provider.
- Wrong check on error message.
=> Fix deployment provider

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Add verbose output to deplpy provider in order to help debug deployment issues.
=> Improve deploy provider output

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Deploy is now followed by a target reboot for ESP32 (improves start of debugging session).
- Remove existing reboot for ESP32 before deployment. Doesn't make sense anymore.
- Fix output for init device retry counter message.
- Fixes intermittent difficulties when starting a debug session from VS.
=> Improvements in deploy provider

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
- Replace SelectedDevice with PreviousSelectedDeviceDescription.
- Minor code rearrangement to optimize workflow.
- Fixes nanoFramework/Home#368.
=> Fix issues with reseting target

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs
- Update several methods to make them async.
- Update code accordingly.
- Remove unused code/methods.
- General code improvement to follow VS extensibility analysers and following async/await patterns.
- Addresses partially nanoFramework/Home#369.
=> Improvements and fixes related with several async and await calls

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Add extra wait after erasing deployment area and upcoming CLR reboot.
- Trying to address random issues when deploying to ESP32 targets.
=> Improvement in deploy provider

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Changes in the workflow to address dificulties with ESP32 deployment.
- Improvements in debug messages.
- Add back-off strategy when waiting for device to leave initialization state.
- Another attempt to improve debug start experience, mostly for ESP32 developers.
=> Improve deploy provider

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs
- Replace parameter on config await.
=> Fix issues with device selection on treeview

source/VisualStudio.Extension/NanoFrameworkPackage.cs, source/VisualStudio.Extension/ResXFileCodeGenerator/NFResXFileCodeGenerator.cs
- Revert some changes of PR#338.
- Related with async access to providers that were causing instabilities.
=> Revert some changes of PR#338

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs
- Fix wrong option being passed to update button handler.
=> Fix wrong option being passed to update button handler

source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
- Update NuGet to 1.0.1-preview-058.
- Update sub-module  @d55a1d4c.
=> Update debugger lib to 1.0.1-preview-058

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
- Remove duplicate headers in device capabilities output.
- The headers are now in the ToString call.
=> Remove duplicate headers in device capabilities output

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Fix bug with second attempt to perform deployment.
- Add ProgressReport to output debug messages.
=> Work on DeployProvider

source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs
- Rework code in EnsureProcessIsInInitializedState.
- Rework code in StartClr.
- Improve target debugger engine start.
- Move several constants from methods to class scope.
- Add several detailed messages on step/status as debugging helpers.
- Minor code clean-up.
- Serious improvement in starting a debug session.
=> Work on CorDebugProcess

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Add decompiler options to prevent resolutions exceptions from being thrown.
- Fixes issue with assembly resolution when reading assembly metadata on deployment preparation.
=> Fix deployment issue with assembly resolution

source/VisualStudio.Extension-2019/NanoFrameworkPackage.cs, source/VisualStudio.Extension/NanoFrameworkPackage.cs
- Replace deprecated auto load attributes with new ones.
- Solves long time warning about deprecated attributes that would prevent the extension from working in a coming VS2019 version.
=> Replace deprecated auto load attributes

source/VisualStudio.Extension-2019/NanoFrameworkPackage.cs, source/VisualStudio.Extension/NanoFrameworkPackage.cs
- Remove autoload attribute.
- Solves long time warning about deprecated attributes that would prevent the extension from working in a coming VS2019 version.
=> Remove autoload attributes from package

source/VisualStudio.Extension-2019/NanoFrameworkPackage.cs, source/VisualStudio.Extension/NanoFrameworkPackage.cs
- Improvements in VS Package initialization regarding initialization and calls of services.
- Rework NanoDeviceCommService property initialization. 
- Fixes issues and warnings with extension loading.
=> Further improvements in async calls on package load

source/CSharp.BlankApplication/CSharp.BlankApplication-vs2019.vstemplate, source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary-vs2019.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension-2019/packages.config, source/VisualStudio.Extension-2019/source.extension.vsixmanifest, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
- Update NuGets for the various project templates.
=> Update NuGets for the various project templates

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/Utilities/DeploymentImageGenerator.cs
- The managed application content was being added at a wrong address in the binary file.
- Minor improvement in the deploy provider code.
- Fix flash dump file name.
=> Fix deployment image generator

source/VisualStudio.Extension/NanoFrameworkMoniker.imagemanifest, source/VisualStudio.Extension/NanoFrameworkMoniker.vsct, source/VisualStudio.Extension/NanoFrameworkPackage.vsct
- Fix catalogue guid and image id for settings (possible confusion with other "settings" string).
- Fixes issue with missing project icon on solution explorer.
=> Fix inconsistencies on image ids in catalogs and resources

source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.csproj
- Replace all images in xaml format as project resources.
- This is the proper way to add those xaml images, not as a xaml page.
=> Replace all images in xaml format as project resources

source/VisualStudio.Extension/NanoFrameworkMoniker.imagemanifest
=> Fix wrong image ID for settings icon

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
- Add async delegates wrappers to most toolbar command handlers.
- Add async delegates wrappers to some calls in deploy provider.
- Minor updates in code as required per the above.
- Improve UI responsiveness and works towards a smoother integration with VS.
=> General improvements in UI responsiveness

source/Tools.MetaDataProcessor/Info_Win32.cpp, source/Tools.MetaDataProcessor/MetaDataProcessor.cpp
- Assembly version is now set to 0 because it's coming from AssemblyNativeVersion.
- Add comment to template to prompt developer to check for version correctness.
- Bump MDP version to 1.10.0
=> Update native assembly generator in MDP

source/Tools.CorHelper/CorHelper-vs2019.vcxproj, source/Tools.CorHelper/CorHelper.vcxproj, source/Tools.MetaDataProcessor/MetaDataProcessor-vs2019.vcxproj, source/Tools.MetaDataProcessor/MetaDataProcessor.vcxproj, source/Tools.Parser/Parser-vs2019.vcxproj, source/Tools.Parser/Parser.vcxproj
- Windows target version is now 10.0.17763.0.
=> Update target version of MDP projects

source/Tools.MetaDataProcessor/MetaDataProcessor.cpp, source/Tools.Parser/AssemblyParser.cpp, source/Tools.Parser/ByteCodeParser.cpp, source/Tools.Parser/FileStore_Win32.cpp
- Add code to set error message description on several locations.
- Add code to add error description to MDP output.
- Bump MDP version to 1.11.0.
- Update nf-interpreter sub-module @ff802306e.
- Closes nanoFramework/Home#174.
- By building several projects simulating possible errors.
=> MDP now outputs description of errors

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Add System.Net.Http to the exception list.
- This assembly was missing in the exception list thus preventing deployment of projects referencing it.
=> Fix deployment provider with System.Net.Http

source/VisualStudio.Extension/Utilities/DeploymentImageGenerator.cs
- Improvements in code taking advantage of new SystemInfo Target property.
=> Improve DeploymentImageGenerator

source/CSharp.BlankApplication/Program.cs, source/CSharp.ClassLibrary/Class1.cs
- Add comments to console and class lib templates pointing to relevant URLs.
=> Update project templates

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
- Add handler to update button availability before command is executed and afterwards.
- Rename other method to make it clear the intended usage.
- Fixes/Closes/Resolves nanoFramework/Home#490.
=> Rework buttons availability in device explorer

source/CSharp.ClassLibrary/Class1.cs
- Address nanoFramework/Home#495.
=> Update documentation URL in Class template

source/CSharp.BlankApplication/Program.cs
- Address nanoFramework/Home#495.
=> Update documentation URL in application template

source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension-2019/packages.config, source/VisualStudio.Extension-2019/version.json, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/version.json
=> Update debugger library to 1.3.0-preview.11

source/VisualStudio.Extension-2019/Rules/EmbeddedResource.BrowseObject.xaml, source/VisualStudio.Extension-2019/Rules/EmbeddedResource.xaml, source/VisualStudio.Extension-2019/Rules/None.BrowseObject.xaml, source/VisualStudio.Extension-2019/Rules/none.xaml, source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension/Rules/EmbeddedResource.BrowseObject.xaml, source/VisualStudio.Extension/Rules/EmbeddedResource.xaml, source/VisualStudio.Extension/Rules/None.BrowseObject.xaml, source/VisualStudio.Extension/Rules/none.xaml, source/VisualStudio.Extension/VisualStudio.Extension.csproj
- Update several rule files to allow adding resource files.
- Fixes nanoFramework/Home#470.
=> Update several rules files

README.md, azure-pipelines.yml
- Update Azure Pipeline yaml.
- Update readme with new instructions, URLs and badges.
- MyGet is becoming more and more problematic with space restrictions.
=> Replace MyGet publish with Open VSIX gallery

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Some people are missing the announcements on the changes with the NuGet development feed. This is an attempt to clearly point the solution to anyone facing deployment issues on NuGet mismatches.
=> Add detailed instruction for NuGet issues

source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension-2019/packages.config, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
- Update NuGet to 1.5.0-preview.11.
- Update sub-module @16b6ced0.
=> Update debugger library to 1.5.0-preview.11

source/VisualStudio.Extension/DebugLauncher/NanoDebuggerLaunchProvider.cs
- Stability improvements on debugger launcher.
- Update  debugger sub-module @ 16b6ced.
=> Stability improvements on debugger launcher

source/Tools.BuildTasks/MetaDataProcessorTask.cs, source/VisualStudio.Extension-2019/Rules/general.browseobject.xaml, source/VisualStudio.Extension/Rules/general.browseobject.xaml
- Replace rules in project options.
- Add new outputs to metadata processor task.
- Remove unused build property and replace with the correct one for the new tool.
=> Replace MDP output option with Verbose

source/Tools.BuildTasks-2019/Tools.BuildTasks.csproj, source/Tools.BuildTasks/MetaDataProcessorTask.cs, source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/Tools.BuildTasks/packages.config, source/VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets, source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension-2019/packages.config, source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
- Update MDP NuGet.
- Remove deprecated options.
- Update code to follow latest MDP workflow.
- Update MDP targets to remove unused/unsupported properties and adjust a couple of others.
- Bring MDP up to date with library.
=> Update MDP task

source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/Tools.BuildTasks/packages.config, source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension-2019/packages.config, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
- Update MDP to 2.10.10.
- Fixes nanoFramework/Home#566
=> Update MDP to 2.10.10

source/Tools.BuildTasks-2019/Tools.BuildTasks.csproj, source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/Tools.BuildTasks/packages.config, source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension-2019/packages.config, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
=> Update MDP to 2.10.14

source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension-2019/packages.config, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
=> Update debugger lib to 1.7.0-preview.12

source/Tools.BuildTasks-2019/Tools.BuildTasks.csproj, source/Tools.BuildTasks-2019/version.json, source/Tools.BuildTasks/MetaDataProcessorTask.cs, source/Tools.BuildTasks/Properties/AssemblyInfo.cs, source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/Tools.BuildTasks/packages.config, source/Tools.BuildTasks/version.json, source/VisualStudio.Extension-2019/Rules/general.browseobject.xaml, source/VisualStudio.Extension-2019/Targets/NFProjectSystem.Default.props, source/VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets, source/VisualStudio.Extension-2019/Targets/NFProjectSystem.props, source/VisualStudio.Extension/Rules/general.browseobject.xaml, source/VisualStudio.Extension/Targets/NFProjectSystem.Default.props, source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets, source/VisualStudio.Extension/Targets/NFProjectSystem.props
- Add processing of assembly metadata dump on MDP.
- Remove deprecated msbuild properties from MDP targets.
- Update project system props
- Update rules xaml
- Remove deprecated output cmd line output.
- Add nbgv to build tasks projec.
- Expose option to dump assembly metadata.
- Remove unused and deprecated properties.
- Add automated version to build tasks DLL.
=> Work MDP task

source/Tools.BuildTasks-2019/Tools.BuildTasks.csproj, source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/Tools.BuildTasks/packages.config, source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension-2019/packages.config, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
=> Update MDP to 2.11.1

source/Tools.BuildTasks/MetaDataProcessorTask.cs, source/VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets, source/VisualStudio.Extension-2019/Targets/NFProjectSystem.props, source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets, source/VisualStudio.Extension/Targets/NFProjectSystem.props
- Add default values for some properties.
- Add missing properties to MetaDataProcessorTask in regular builds.
- Sync MDP.targets between VS 2017 and 2019.
- Remove unused properties from targets and corresponding MDP task parameters.
- Cleanup unused build properties.
- Tidy up target files.
=> Work project system files

source/VisualStudio.Extension-2019/Rules/general.browseobject.xaml, source/VisualStudio.Extension-2019/Targets/NFProjectSystem.props, source/VisualStudio.Extension-2019/Targets/NFProjectSystem.targets, source/VisualStudio.Extension/Rules/general.browseobject.xaml, source/VisualStudio.Extension/Targets/NFProjectSystem.props, source/VisualStudio.Extension/Targets/NFProjectSystem.targets
- Move several properties from props to targets.
- Update XAML to match new/changed property names.
=> Work project system

source/Tools.BuildTasks-2019/Tools.BuildTasks.csproj, source/Tools.BuildTasks-2019/version.json, source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/Tools.BuildTasks/packages.config, source/Tools.BuildTasks/version.json, source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension-2019/packages.config, source/VisualStudio.Extension-2019/version.json, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/version.json
- Bump build tasks to 1.7.
- Bump version to 1.6.
- Clean up and tidy up VS2019 proj file.
- Update MDP with last version.
- Fixes nanoFramework/Home#569.
=> Update MDP to 2.19.

source/Tools.BuildTasks/MetaDataProcessorTask.cs, source/VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets, source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets
- Rework MDP to properly support Interop skeleton when calling MDP task.
- Clean up MDP targets file.
- Add new parameter GenerateStubs to MDP task.
- Update MDP targets accordingly.
- Add support for Interop skeleton generation.
- Clean up a messy MDP targets file.
=> Work to support Interop skeleton

source/Tools.BuildTasks-2019/Tools.BuildTasks.csproj, source/Tools.BuildTasks/MetaDataProcessorTask.cs, source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/Tools.BuildTasks/packages.config, source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension-2019/packages.config, source/VisualStudio.Extension-2019/version.json, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/version.json
=> Update MDP to 2.20.0

source/Tools.BuildTasks-2019/Tools.BuildTasks.csproj, source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/Tools.BuildTasks/packages.config, source/VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets, source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension-2019/packages.config, source/VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
- Minor changes in MDP targets file to adjust to the latest MDP changes.
=> Update MDP to 2.21.3

source/CSharp.ClassLibrary/AssemblyInfo.cs
- Add AssemblyNativeVersion attribute to class library template.
- Attribute is required when creating class library that uses Interop.
=> Add AssemblyNativeVersion attribute to class library template

source/Tools.BuildTasks-2019/Tools.BuildTasks.csproj, source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/Tools.BuildTasks/packages.config, source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension-2019/packages.config, source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/packages.config
- Closes nanoframework/Home#573.
=> Update MDP to v2.22.7

source/VisualStudio.Extension-2019/NanoFrameworkPackage.cs, source/VisualStudio.Extension/NanoFrameworkPackage.cs
Project files do not show in window when adding existing projects.
When adding an existing project to a solution, nfproj files are hidden from the file dialog.
nfproj files do not show in the file dialog so they can't be clicked to add. You must type the file name.
I added existing projects to a solution.
Signed-off-by: manuelxmarquez
=> Fix project files not showing in dialog window when adding existing projects

source/VisualStudio.Extension-2019/NanoFrameworkPackage.cs, source/VisualStudio.Extension/DeployProvider/DeployProvider.cs, source/VisualStudio.Extension/MessageCentre/MessageCentre.cs, source/VisualStudio.Extension/NanoFrameworkPackage.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs
- Add check for object null on GetService calls.
- Improvements in extension async package.
- Improvements in device explorer.
- Improvements in message center.
- Improvements suggested by analysers and Sonarcloud rules.
- Work on experimental instance.
=> General improvements

source/Tools.BuildTasks/Tools.BuildTasks.csproj, source/Tools.BuildTasks/packages.config, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/app.config, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/version.json, source/nanoFramework.Tools.VisualStudio.sln, source/readme.md
- Bump version to 2017.1.8.
- Add readme with dev notes.
=> Update NuGets in VS2017

source/Tools.BuildTasks-2019/Tools.BuildTasks.csproj, source/Tools.BuildTasks-2019/packages.config, source/VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs, source/VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension-2019/app.config, source/VisualStudio.Extension-2019/packages.config, source/VisualStudio.Extension-2019/version.json, source/nanoFramework.Tools.VisualStudio-2019.sln, source/readme.md
- Bump version to 2019.1.8.
- Add developer notes doc.
=> Update NuGets in VS2019

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
When you right click a project to deploy or have an item selected in the solution explorer and use the build menu to deploy, it says deploying in the output window but nothing happens.
This is because the DeployProvider uses the startup project. I fixed this issue as well by not using the startup project to determine which project to deploy.
Using the context menu in visual studio to deploy a project will attempt to deploy a different project than the one the user selects.
I used the right click context menu in the solution explorer to deploy a project. Also used the context menu at the top of visual studio to deploy the project that is currently open. Also works with a hot key.
Signed-off-by: manuelxmarquez
=> Fix deploy project from context menu.

source/VisualStudio.Extension-2019/Targets/NFProjectSystem.props, source/VisualStudio.Extension/Targets/NFProjectSystem.props
- Add property to disable package conflict resolution.
- Trying to improve the existing issues with package references mismatch. 
=> Improvements in project system props

source/Tools.BuildTasks/MetaDataProcessorTask.cs
- Set environment variable with native checksum for assembly.
- Need to access this data outside the build environment.
=> Expose native checksum in environment variable

source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs
- Fix order and content of reboot message.
- Fixes reboot message with device description.
- Closes #416.
=> Various fixes 

source/VisualStudio.Extension/CorDebug/CorDebugValue.cs
- Add check for null value.
- Previous code throwed an exception on null value. Now it outputs a nice message to the nF messages console.
=> Improve GetFieldValue

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Improve working of the deployment error message. Hopefully it's more helpful.
- Trying to make it more helpful.
=> Improve deployment error message

source/CSharp.BlankApplication/Program.cs
Console.WriteLine has been depreciated.
=> Updates template to use Debug.WriteLine

source/VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml, source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension/Converters/Wireless80211_OptionsTypeConverter.cs, source/VisualStudio.Extension/Converters/WirelessAP_OptionsTypeConverter.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml, source/VisualStudio.Extension/Utilities/EnumToItemsSource.cs, source/VisualStudio.Extension/VisualStudio.Extension.csproj
- Add new converters for wireless configs.
- Rework EnumToItemsSource converster to remove 0 (None/Unknow) enum items.
- Update network config dialog to show new option drop down.
- ESP32 network configuration is now possible.
- Using experimental instance to config ESP32 device.
Signed-off-by: GITHUB_USER <GITHUB_USER_EMAIL>
=> Improve network config dialog

source/CSharp.BlankApplication/CSharp.BlankApplication-vs2019.vstemplate, source/CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary-vs2019.vstemplate, source/CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj, source/VisualStudio.Extension-2019/packages.config, source/VisualStudio.Extension-2019/source.extension.vsixmanifest, source/VisualStudio.Extension/VisualStudio.Extension.csproj, source/VisualStudio.Extension/VisualStudio.Extension.previous.nugetreferenceswitcher, source/VisualStudio.Extension/packages.config, source/VisualStudio.Extension/source.extension.vsixmanifest
Update mscorlib NuGet package in template project to v1.7.3 (stable)
=> Update mscorlib NuGet package in template project to v1.7.3 (stable)

source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
- List of missing assemblies on the target wasn't being properly populated.
=> Fix issue with deploy provide listing missing assemblies

source/VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml, source/VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs, source/VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, source/VisualStudio.Extension-2019/version.json, source/VisualStudio.Extension/MessageCentre/MessageCentre.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs, source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, source/VisualStudio.Extension/version.json
- Rework code to manage devices treeview. Improved responsiveness and style.
- Add new style to improve tree items look.
- Rework data context access variable in network configuration control.
- Minor code style improvements.
- Bump version to 2.1.
- UI improvements and responsiveness.
=> UI improvements

VisualStudio.Extension-2019/Targets/NFProjectSystem.Default.props, VisualStudio.Extension/Targets/NFProjectSystem.Default.props
- Change DebugType to portable for release builds.
- Required to comply with Source Link.
=> Update project system target to build portable debug symbols on release

VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets, VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets
- Remove condition from targets file for native checksum output only on Azure Pipelines.
- The existing condition is not working and the output is not occurring. Because outputting is not harmful at all in any type of build, removing this.
=> Remove condition from targets for native checksum output

VisualStudio.Extension-2019/source.extension.vsixmanifest, VisualStudio.Extension/source.extension.vsixmanifest
-Update manifest to use logo with 128px.
- To comply with VS extension publishing guidelines for marketplace.
=> Update VS extension logo to 128px to comply with guidelines

VisualStudio.Extension-2019/Targets/NFProjectSystem.CSharp.targets, VisualStudio.Extension/Targets/NFProjectSystem.CSharp.targets
- Add LangVersion (7.3) to project system targets.
- As we are "kind of in sync" with .NET Framework and that's the default language version there, this is added for convenience.
See documentation [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults).
=> Add LangVersion to project system targets

VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml, VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, VisualStudio.Extension-2019/version.json, VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml, VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs, VisualStudio.Extension/version.json
- Add General tab and file dialog to allow uploading a CA root certificate bundle to target.
- Bump version to x.2.3.
=> Add CA root certificate upload to network dialog

Tools.BuildTasks/ProcessResourceFiles.cs
- Add support to handle ICO files.
- Rework code to handle as binary resource pretty much everything that's not one of the other know resource types.
- Rework code for efficiency.
- Improves resource handling.
=> Improve resource processing

Tools.BuildTasks/Utilities/DebuggerHelper.cs
- Code now checks explicitly for user environment variable.
- Add compiler define check to prevent helper code to make it release.
- Improve how it works: wasn't clear on what would be the scope of the env variable. Also make sure the help code doesn't make to release.
=> Improve debug helper

VisualStudio.Extension-2019/NanoFrameworkPackage.vsct, VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs, VisualStudio.Extension/NanoFrameworkPackage.vsct, VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
- Button is now a menu.
- Add options to reboot CLR, reboot to nanoBooter, reboot to bootloader.
- Improve reboot options by exposing all possibilities.
=> Improve reboot button

VisualStudio.Extension-2019/FirmwareUpdate/BintrayPackageInfo.cs, VisualStudio.Extension-2019/FirmwareUpdate/CC13x26x2Firmware.cs, VisualStudio.Extension-2019/FirmwareUpdate/Esp32Firmware.cs, VisualStudio.Extension-2019/FirmwareUpdate/FirmwarePackage.cs, VisualStudio.Extension-2019/FirmwareUpdate/Stm32Firmware.cs, VisualStudio.Extension-2019/FirmwareUpdate/UpdateManager.cs, VisualStudio.Extension-2019/NanoFrameworkPackage.cs, VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml, VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs, VisualStudio.Extension-2019/VisualStudio.Extension.csproj, VisualStudio.Extension-2019/version.json, VisualStudio.Extension/MessageCentre/MessageCentre.cs, VisualStudio.Extension/NanoFrameworkPackage.cs, VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs, VisualStudio.Extension/ToolWindow.DeviceExplorer/SettingsDialog.xaml, VisualStudio.Extension/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs, VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs, VisualStudio.Extension/VisualStudio.Extension.csproj, VisualStudio.Extension/version.json, nanoFramework.Tools.VisualStudio-2019.sln
- Add new properties to control updates.
- Expose these in Device Explorer settings dialog.
- Add UpdateManager class.
- Add firmware package classes.
- Update DeviceExplorer view model to launch updates and interact with the service.
- Bump versions to nnnn.3.0.
- Update nf-debuger sub-module @ 52a60a6.
- Adds auto-update for STM32 targets. The other platforms will follow.
=> Add auto-update

VisualStudio.Extension-2019/AutomaticUpdates/UpdateManager.cs
- Fix conditions on auto update manager.
=> Fix conditions on auto update manager

VisualStudio.Extension-2019/AutomaticUpdates/UpdateManager.cs
- Fix condition to check for update for returning device.
- Replace cache key from GUID to device description.
=> Fixes in update manager

VisualStudio.Extension/CorDebug/CorDebugProcess.cs, VisualStudio.Extension/DeployProvider/DeployProvider.cs, VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
- Update several code bits to use new properties.
- Update debugger sub module to 1fbc74b
=> Improvements after changes in debugger library

VisualStudio.Extension/DeployProvider/DeployProvider.cs, VisualStudio.Extension/MessageCentre/MessageCentre.cs, VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
- Update API calls following debugger library changes.
- Add new API for message centre to output detailed progress operation.
- Wrap erase step in deploy provider.
- Update debugger sub-module.
- Update calls required by changes in debugger API.
- Improve output and user feedback on long running operations.
=> Improve deploy and erase output

azure-pipelines.yml, config/filelist.txt, config/signClient.json
- VSIX packages are now signed.
=> Add code signing to VSIX packages

VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Add extra yield to improve responsiveness.
- Second deploy attempt can't skip erase.
- Progress report indicators weren't being assigned as they should.
=> Fix deploy provider

VisualStudio.Extension/CorDebug/CorDebugProcess.cs
- Remove unused code and comments.
- Remove unnecessary call to SetExecutionMode.
- Remove unnecessary calls to assert ShuttingDown flag.
- Improves debug session start.
=> Work debug start

VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets, VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets
- Fix condition by properly comparing strings.
- Fix path on alternative location, was missing a \.
=> Fix MDP targets file

VisualStudio.Extension-2019/AutomaticUpdates/UpdateManager.cs, VisualStudio.Extension-2019/NanoFrameworkPackage.cs, VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml, VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs, VisualStudio.Extension/NanoFrameworkPackage.cs, VisualStudio.Extension/ToolWindow.DeviceExplorer/SettingsDialog.xaml, VisualStudio.Extension/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
- Change labels in dialog, storage vars and handlers.
- Improve consistency and wording for the automatic updates.
=> Changes in wording for automatic update options

VisualStudio.Extension-2019/NanoFrameworkPackage.cs, VisualStudio.Extension-2019/VSPackage.resx, VisualStudio.Extension-2019/VisualStudio.Extension.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2019/version.json
- Package description was wrongly refering to 2017.
- Resource name was wrong for 2019 version.
- Update NuGet packages.
- Bump version to 2019.4.1.
- Bring Nugets and references in VS2019 up to date.
- Fix reported issues with newer VS 2019 version on Windows server setups.
=> Various fixes with 2019 extension

VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets, VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets
- Add information message on MDP location overridden
- Improves feedback to developer.
=> Add information message on MDP location overridden

VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets, VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets
- Update conditions to set output var only on CI builds.
- Unseful output removed from local builds.
=> Update conditions to set output var only on CI builds

CSharp.BlankApplication/CSharp.BlankApplication-vs2019.vstemplate, CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, CSharp.ClassLibrary/CSharp.ClassLibrary-vs2019.vstemplate, CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, VisualStudio.Extension-2019/VisualStudio.Extension.GeneratedMSBuildEditorConfig.editorconfig, VisualStudio.Extension-2019/VisualStudio.Extension.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2019/source.extension.vsixmanifest, VisualStudio.Extension/VisualStudio.Extension.csproj, VisualStudio.Extension/packages.lock.json, VisualStudio.Extension/source.extension.vsixmanifest
- Update NuGet in template projects
=> Update NuGet in template projects

CSharp.BlankApplication/NFApp.nfproj, CSharp.ClassLibrary/NFClassLibrary.nfproj, CSharp.TestApplication/NFUnitTest.nfproj, Tools.BuildTasks-2019/Tools.BuildTasks.csproj, Tools.BuildTasks/Tools.BuildTasks.csproj, VisualStudio.Extension-2019/Targets/NFProjectSystem.CSharp.targets, VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets, VisualStudio.Extension-2019/Targets/NFProjectSystem.props, VisualStudio.Extension-2019/Targets/NFProjectSystem.targets, VisualStudio.Extension/Targets/NFProjectSystem.CSharp.targets, VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets, VisualStudio.Extension/Targets/NFProjectSystem.props, VisualStudio.Extension/Targets/NFProjectSystem.targets, nanoFramework.Tools.VisualStudio.sln
- Update tools version on all projects.
- Bring project files up to date.
=> Work CI-CD

VisualStudio.Extension-2019/VisualStudio.Extension.csproj, VisualStudio.Extension-2019/packages.lock.json
=> Update VS2019 NuGets

VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml, VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml, VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs
- Add support for device certificates.
- Add option to clear Root CA and device certificates.
- Minor cosmetic changes to Network Config dialog.
=> Improve device certificate management

VisualStudio.Extension-2019/NanoFrameworkPackage.cs, VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml, VisualStudio.Extension/NanoFrameworkPackage.cs, VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml
- Minor improvements in messages and outputs.
- Typos, wrong alignments, missing names.
=> Improvements in messages and outputs

VisualStudio.Extension-2019/AutomaticUpdates/CC13x26x2Firmware.cs, VisualStudio.Extension-2019/AutomaticUpdates/CloudsmithPackageInfo.cs, VisualStudio.Extension-2019/AutomaticUpdates/Esp32Firmware.cs, VisualStudio.Extension-2019/AutomaticUpdates/FirmwarePackage.cs, VisualStudio.Extension-2019/AutomaticUpdates/Stm32Firmware.cs, VisualStudio.Extension-2019/NanoFrameworkPackage.cs, VisualStudio.Extension-2019/VisualStudio.Extension.csproj, VisualStudio.Extension/NanoFrameworkPackage.cs, VisualStudio.Extension/VisualStudio.Extension.csproj
- Update automatic updates class to use new repo.
- Change default of AutoUpdate user option to false.
- Part of the move to Cloudsmith.
=> Replace Binray repo with Cloudsmith

VisualStudio.Extension-2019/VisualStudio.Extension.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension/VisualStudio.Extension.csproj, VisualStudio.Extension/packages.lock.json
=> Cleanup references

VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets, VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets
- Improve setting environment vars for builds running in Azure Pipelines.
- Required to grab native checksum.
=> Update targets for build in Azure pipelines

VisualStudio.Extension/CorDebug/CorDebugProcess.cs
- Rework sequence.
- Add Thread.Yeld calls to back-off from serial channel allowing pauses between packets.
- Fixing issues with debug engine attachement.
=> Improvements in debug attach sequence

VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets, VisualStudio.Extension/Targets/NFProjectSystem.MDP.targets
- Fix native checksum output in targets0
- The output of this build variable was failing on solutions that have tests.
=> Fix native checksum output in targets

VisualStudio.Extension/Targets/NFProjectSystem.Default.props
- Revert LangVersion to 7.3 for VS2017.
- VS2017 doesn't support 9.0.
=> Revert LangVersion to 7.3 for VS2017

VisualStudio.Extension/CorDebug/CorDebugProcess.cs
- Improve sequence of debug start.
- Update debugger sub-module @ 8e59558.
- Fixes nanoFramework/Home#755.
=> Improve sequence of debug start

VisualStudio.Extension/DeployProvider/DeployProvider.cs
- Remove erase step and setting device to known execution state.
- No need to erase device and set it to stop execution. All this it's already performed in the following steps. It was introduced as a workaround for devices that where misbehaving during deployment.
=> Simplification of DeployProvider

VisualStudio.Extension/CorDebug/CorDebugProcess.cs
- Add new messages on debug session start.
- Provide more detailed feedback, useful when debugging issue in this situation.
=> Improvements in output messages on debug session start

CSharp.BlankApplication/CSharp.BlankApplication-vs2017.vstemplate, CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, CSharp.ClassLibrary/CSharp.ClassLibrary-vs2017.vstemplate, CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, CSharp.TestApplication/CSharp.TestApplication-vs2017.vstemplate, CSharp.TestApplication/CSharp.TestApplication.vstemplate, CSharp.TestApplication/NFUnitTest.nfproj, VisualStudio.Extension-2019/VisualStudio.Extension.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2019/source.extension.vsixmanifest, VisualStudio.Extension/VisualStudio.Extension.csproj, VisualStudio.Extension/packages.lock.json, VisualStudio.Extension/source.extension.vsixmanifest
=> Update template projects with latest NuGets

VisualStudio.Extension/CorDebug/CorDebugAppDomain.cs
- This is now loading the assembly as expected.
- Rework output warning about the missing debug symbols.
- Properly handles these situation.
- Related with nanoFramework/Home#732.
=> Fix handling of load assembly event

VisualStudio.Extension-2019/VisualStudio.Extension.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension/VisualStudio.Extension.csproj, VisualStudio.Extension/packages.lock.json
- Add back this library.
- This library has being wrongly removed during automated updates 1318c7ffe50a08d7929eb37b3fdb01711fed998d and 250f0d15dae3519605b2f1ddec9539a272db1926.
- Resolves nanoFramework/Home#788.
=> Fix missing MetadataProcessor.MsBuildTask reference

CSharp.BlankApplication/CSharp.BlankApplication-vs2017.vstemplate, CSharp.BlankApplication/CSharp.BlankApplication.vstemplate, CSharp.ClassLibrary/CSharp.ClassLibrary-vs2017.vstemplate, CSharp.ClassLibrary/CSharp.ClassLibrary.vstemplate, CSharp.TestApplication/CSharp.TestApplication-vs2017.vstemplate, CSharp.TestApplication/CSharp.TestApplication.vstemplate, CSharp.TestApplication/NFUnitTest.nfproj, VisualStudio.Extension-2019/VisualStudio.Extension.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2019/source.extension.vsixmanifest, VisualStudio.Extension/VisualStudio.Extension.csproj, VisualStudio.Extension/packages.lock.json, VisualStudio.Extension/source.extension.vsixmanifest
=> Update nugets for template projects

VisualStudio.Extension/CorDebug/CorDebugProcess.cs
Minor improvements to text to make the debug output more clear.
OCD improvements.
N/A, but requires a review!
=> Improvements in debugger informational messages

VisualStudio.Extension-2019/version.json, VisualStudio.Extension/NanoDeviceCommService/NanoDeviceCommService.cs, VisualStudio.Extension/version.json
- Debug client is now created from composite port of serial and network clients.
- Update debugger sub-module @0412dcc.
- Bump version to 2017.7.0 and 2019.7.0.
- Supersedes #651.
- Continuing work towards network debugging and support for virtual device.
=> Add network port base

CSharp.AssemblyInfoTemplate/CSharp.AssemblyInfoTemplate.csproj, CSharp.TestApplication/CS.TestApplication-vs2017.vstemplate, CSharp.TestApplication/CS.TestApplication-vs2019.vstemplate, CSharp.TestApplication/CS.TestApplication-vs2022.vstemplate, CSharp.TestApplication/NFUnitTest.nfproj, NuGet.Config, VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2019/source.extension.vsixmanifest, VisualStudio.Extension-2019/version.json, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json, VisualStudio.Extension-2022/source.extension.vsixmanifest, VisualStudio.Extension-2022/version.json
- Update several NuGets for VS2022 and VS2019.
- Bump versions.
=> Update several NuGets 

VisualStudio.Extension-2022/NanoFrameworkPackage.cs, VisualStudio.Extension-2022/NanoFrameworkPackage.vsct, VisualStudio.Extension-2022/packages.lock.json, VisualStudio.Extension-2022/source.extension.vsixmanifest
- Replace GUIDs for package.
- Images missing on all menus in VS2022.
=> Fix missing images for VS menu items

VisualStudio.Extension-2022/source.extension.vsixmanifest
- Fix version.
- Fix URL to changelog.
- Fix declaration of MPF component.
=> Fix VS2022 manifest file

azure-pipelines.yml
- Fix conditions.
- Add correct tag for VS2022 tasks.
- Fix yaml style.
=> Fix changelog generator job

vs-extension.shared/DebugLauncher/NanoDebuggerLaunchProvider.cs, vs-extension.shared/DeployProvider/DeployProvider.cs
- Add output with details of running VS extension library.
- Remove usings and tidy up code.
- Improve output of debug messages.
=> Improve output details for deploy and debug launch providers

vs-extension.shared/NanoDeviceCommService/NanoDeviceCommService.cs
- Improve instantiation of serial and network ports before creation of composite ort.
- Improve comments for clarity/bringing up to date.
- Fix variable name to follow project code style.
=> Improvements in debug client instantiation

VisualStudio.Extension-2022/NanoFrameworkMoniker.imagemanifest, VisualStudio.Extension-2022/NanoFrameworkMoniker.vsct, VisualStudio.Extension-2022/NanoFrameworkPackage.cs, VisualStudio.Extension-2022/NanoFrameworkPackage.vsct, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, vs-extension.shared/NanoFrameworkMonikers.cs, vs-extension.shared/ToolWindow.DeviceExplorer/DeviceExplorer.cs, vs-extension.shared/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
- Regenerate GUIDs for package and commands.
- Update code accordingly.
- Fixes nanoFramework/Home#901.
=> Regenerate GUIDs for package and commands

CSharp.BlankApplication/CS.BlankApplication-vs2017.vstemplate, CSharp.BlankApplication/CS.BlankApplication-vs2019.vstemplate, CSharp.BlankApplication/CS.BlankApplication-vs2022.vstemplate, CSharp.ClassLibrary/CS.ClassLibrary-vs2017.vstemplate, CSharp.ClassLibrary/CS.ClassLibrary-vs2019.vstemplate, CSharp.ClassLibrary/CS.ClassLibrary-vs2022.vstemplate, CSharp.TestApplication/CS.TestApplication-vs2017.vstemplate, CSharp.TestApplication/CS.TestApplication-vs2019.vstemplate, CSharp.TestApplication/CS.TestApplication-vs2022.vstemplate, CSharp.TestApplication/NFUnitTest.nfproj, VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2019/source.extension.vsixmanifest, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json, VisualStudio.Extension-2022/source.extension.vsixmanifest
- Update templates and packages configs and extension manifests.
=> Update references used in project templates

VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs
- Var is now nulled on NetworkConfiguration dialog constructor.
=> Improvement in device certificate handling

VisualStudio.Extension-2019/FodyWeavers.xml, VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2022/FodyWeavers.xml, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json
- Add weavers for PropertyChanged.
- Add dependency to PropertyChanged.Fody to make Package Manager happy with Fody version.
- Downgrade version of PropertyChanging.Fody to get closer to requirement of PropertyChanged.
- Fixes mismatches on Fody and friends.
=> Fix Fody dependencies

VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json
=> Update MDP task to new nuget

VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json
- Remove dependency from MetadataProcessor.Core.
=> Remove dependency from MetadataProcessor.Core

VisualStudio.Extension-2022/Targets/NFProjectSystem.MDP.targets
- Fix MDP targets file for VS2022.
- Building a core library was failing in VS2022.
=> Fix building core library in VS2022

VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml, VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/SettingsDialog.xaml
- Replacing from term prone to trouble.
=> Rename label for COM port exclusion list

CSharp.BlankApplication/CS.BlankApplication-vs2017.vstemplate, CSharp.BlankApplication/CS.BlankApplication-vs2019.vstemplate, CSharp.BlankApplication/CS.BlankApplication-vs2022.vstemplate, CSharp.ClassLibrary/CS.ClassLibrary-vs2017.vstemplate, CSharp.ClassLibrary/CS.ClassLibrary-vs2019.vstemplate, CSharp.ClassLibrary/CS.ClassLibrary-vs2022.vstemplate, CSharp.TestApplication/CS.TestApplication-vs2017.vstemplate, CSharp.TestApplication/CS.TestApplication-vs2019.vstemplate, CSharp.TestApplication/CS.TestApplication-vs2022.vstemplate, CSharp.TestApplication/NFUnitTest.nfproj, VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2019/source.extension.vsixmanifest, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json, VisualStudio.Extension-2022/source.extension.vsixmanifest
=> Update refs in template projects

vs-extension.shared/DeployProvider/DeployProvider.cs
- Improve algorithm.
- Made message more concise and hopefully more clear.
- Minor improvements in other messages.
- Removing mentions to preview versions, which aren't used anymore.
- Need to improve the error message to make it more clear.
=> Improve message reporting deployment issues

vs-extension.shared/DeployProvider/DeployProvider.cs
- Rework ExtensionInformationalVersion which was occasionally throwing an obscure null exception on deployment.
- Remove unused usings.
- Fix code format issues.
=> Miscellaneous improvements in Deploy provider

CSharp.AssemblyInfoTemplate/Properties/AssemblyInfo.cs, CSharp.BlankApplication/AssemblyInfo.cs, CSharp.BlankApplication/Properties/AssemblyInfo.cs, CSharp.ClassLibrary/AssemblyInfo.cs, CSharp.ClassLibrary/Properties/AssemblyInfo.cs, CSharp.ClassTemplate/Properties/AssemblyInfo.cs, CSharp.ResourceTemplate/Properties/AssemblyInfo.cs, CSharp.TestApplication/Properties/AssemblyInfo.cs, VisualStudio.Extension-2019/NanoFrameworkPackage.cs, VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, VisualStudio.Extension-2022/NanoFrameworkPackage.cs, VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs
- Various fixes from code analysers.
- Fix assembly info files in templates.
=> Various fixes from code analysers

vs-extension.shared/DeployProvider/DeployProvider.cs
- Check for error condition on assembly versions was wrong.
=> Fix deployment

VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets, VisualStudio.Extension-2022/Targets/NFProjectSystem.MDP.targets
- Build now can update environment vars in github actions to surface this value.
- Improve comments for this and the Azure Pipelines one too.
- Allows setting env var in github actions pipeline.
=> Improve output of NativeChecksum in pipelines

Tools.BuildTasks-2019/Tools.BuildTasks-2019.csproj, VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json
=> Update several nuget packages

VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json, VisualStudio.Extension-2022/source.extension.vsixmanifest
- Update dependencies for VS17.3.
- Also update VSIX manifest to have 17.3 as minimum version for install requirement.
- Need to update build for VS17.3.
- Local build and VS experimental instance.
=> Update dependencies for VS17.3

CSharp.TestApplication/NFUnitTest.nfproj, VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/source.extension.vsixmanifest, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/source.extension.vsixmanifest
- Fix various references to the Unit Test framework.
- Wrong update from Unit Test framework automated update.
- Resolves nanoFramework/Home#1140.
=> Fix references to Unit Test framework

VisualStudio.Extension-2019/Targets/NFProjectSystem.MDP.targets, VisualStudio.Extension-2022/Targets/NFProjectSystem.MDP.targets
- Allow overriding location for nano Build Tasks with env variable.
- Fix typos in comments.
- Fix conditions to override msbuild tasks with custom version.
- Improve log message about overridden msbuild task dll.
- Improves debugging related with msbuild tasks.
=> Improvements in MDP targets

CSharp.TestApplication/.runsettings, CSharp.TestApplication/NFUnitTest.nfproj, CSharp.TestApplication/UnitTest1.cs
- Update runsetting file to latest VS Test requirements.
- Update template.
- Closes nanoFramework/Home#1169.
=> Update Unit Test project template

CSharp.TestApplication/NFUnitTest.nfproj, CSharp.TestApplication/UnitTest1.cs, CSharp.TestApplication/nano.runsettings
- This reverts commit 6b833cfbd86eb05a1aa818fe5ff806adb62cf4ac.
- The new Unit Test template didn't fix the underlying issue and not using nano.runsettings file makes it harder to run unit tests "out-of-box".
- To have a working template requires updating the test framework package to the latest version, which will be taken care of in a subsequent PR.
=> Revert "Update Unit Test project template (#750)"

CSharp.TestApplication/.runsettings, CSharp.TestApplication/NFUnitTest.nfproj
- Fix unit test template .runsettings
=> Fix .runsettings in Unit Test project template 

VisualStudio.Extension-2019/source.extension.vsixmanifest, VisualStudio.Extension-2022/source.extension.vsixmanifest
- Now using URL to github release.
- Resolves nanoFramework/Home#1133.
=> Fixes release notes on VSIX manifest

CSharp.BlankApplication/CS.BlankApplication-vs2019.vstemplate, CSharp.BlankApplication/CS.BlankApplication-vs2022.vstemplate, CSharp.ClassLibrary/CS.ClassLibrary-vs2019.vstemplate, CSharp.ClassLibrary/CS.ClassLibrary-vs2022.vstemplate, CSharp.TestApplication/CS.TestApplication-vs2019.vstemplate, CSharp.TestApplication/CS.TestApplication-vs2022.vstemplate, CSharp.TestApplication/NFUnitTest.nfproj, VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2019/source.extension.vsixmanifest, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json, VisualStudio.Extension-2022/source.extension.vsixmanifest
- Bump nanoFramework.CoreLibrary from 1.12.0 to 1.14.2
- Bump nanoFramework.TestFramework" from 2.0.60 to 2.1.59
=> Bump NuGet versions

VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json, nanoFramework.Tools.VisualStudio.sln
- Update references compatible with VS17.4.
- Release build of VS2022 doesn't deploy VSIX anymore.
=> Update references compatible with VS17.4

VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json
=> Update VS2022 references

VisualStudio.Extension-2022/NanoFrameworkPackage.cs
- Add ProvideCodeBase to fix missing icons in device explorer.
- Following advice to fix missing icons in device explorer.
- Addresses nanoframework/Home#1009.
=> Add ProvideCodeBase to fix missing icons in device explorer

VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json
- Bump nbgv to 3.5.119 in VS2019.
=> Bump nbgv to 3.5.119 in VS2019

VisualStudio.Extension-2022/NanoFrameworkPackage.cs
- Add CodeBase attribute for community MVVM library.
- This is required to allo MVVM library to properly load it's dependencies.
=> Add code base attribute for MVVM community library

VisualStudio.Extension-2022/NanoFrameworkPackage.cs
- Add ProvideService attributes to package declaration.
- Improve package declaration.
=> Add new attributes to package declaration

vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs
- Fix duplicate device scanning on loading.
- Fix regexe expression to process install/update.
- Redirect output of process to allow sending kill process escape char.
- Add loop after exit option to nanoclr launch to keep device running.
- Rework InstallNanoClrTool.
- Rework UpdateNanoClr.
- Virtual device was having issues with starting, installing and updating.
=> Improvements on virtual device

vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs
Part of the issue found when trying to run the test adapter in the CI.
Full message is: ` [nanoTestAdapter]: Exception raised in the process: System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`
=> Fix spelling error

VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2022/packages.lock.json, vs-extension.shared/Utilities/EnumToItemsSource.cs
- Replace DisplayAttribute (from DataAnnotations namespace) with DescriptionAttribute.
- Remove hard dependency on DataAnnotations nuget.
=> Rework ByteEnumToItemsSource

VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml, VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs, VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml, VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs
- Remove duplicated word in handler.
=> Rename method handler for clarity

VisualStudio.Extension-2022/Properties/AssemblyInfo.cs
- Remove wrong attribute for code base.
- Wrongly added in #811.
=> Remove wrong attribute for code base

CSharp.BlankApplication/CS.BlankApplication-vs2019.vstemplate, CSharp.BlankApplication/CS.BlankApplication-vs2022.vstemplate, CSharp.ClassLibrary/CS.ClassLibrary-vs2019.vstemplate, CSharp.ClassLibrary/CS.ClassLibrary-vs2022.vstemplate, CSharp.TestApplication/CS.TestApplication-vs2019.vstemplate, CSharp.TestApplication/CS.TestApplication-vs2022.vstemplate, VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2019/source.extension.vsixmanifest, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json, VisualStudio.Extension-2022/source.extension.vsixmanifest
=> Update templates with mscorlib 1.15.5

vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs
- Correct the `virtualserial` parameter for `nanoclr`
- Fixes nanoFramework/Home#1503
N/A
=> Correct the `virtualserial` parameter for `nanoclr`

CSharp.BlankApplication/CS.BlankApplication-vs2019.vstemplate, CSharp.BlankApplication/CS.BlankApplication-vs2022.vstemplate, CSharp.ClassLibrary/CS.ClassLibrary-vs2019.vstemplate, CSharp.ClassLibrary/CS.ClassLibrary-vs2022.vstemplate, CSharp.TestApplication/CS.TestApplication-vs2019.vstemplate, CSharp.TestApplication/CS.TestApplication-vs2022.vstemplate
The NF projects can now only be found by typing `nanoframework` in the VS2022 UI. That is very clumsy, VS2022 has a much better UI-native way to find projects.
See [Microsoft documentation](https://learn.microsoft.com/en-us/visualstudio/ide/template-tags?view=vs-2022).
Although VS2019 version 16.1+ supports tags as well, no changes are made to the VS2019 templates, as it is not clear to me whether the nanoframework extension should support earlier versions as well.
=> Added tags to project templates to make it easier to find them

vs-extension.shared/CorDebug/DebugPort.cs
Improve popup "Hello from LaunchSuspended!" when run without debug.
With test extension
=> Improve popup message when run without debug

VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json
=> Revert VS2019 refs

VisualStudio.Extension-2022/NanoFrameworkMoniker.imagemanifest, VisualStudio.Extension-2022/PrepareImageManifest.targets, VisualStudio.Extension-2022/Properties/AssemblyInfo.cs, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj
- Add code base for several referenced assemblies that don't match binding redirects VS has registered.
- Add target to adjust image manifest with extension version on build.
- Following advice in https://developercommunity.visualstudio.com/t/Image-icons-from-image-catalog-not-showi/10791720
- Resolves nanoFramework/Home#1009.
=> Implement fixes to get icon images loading

vs-extension.shared/DeployProvider/DeployProvider.cs
Add Content file deployment to internal storage
- Add Content file deployment to internal storage
- Expected behavior:
```
<Content Include="notdeployed.txt" /> => not deployed
<Content Include="text1.txt"> => deployed as "I:\text1.txt"
<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</Content>
<Content Include="text2.txt"> => deployed as "I:\super.txt"
<NF_StoragePath>I:\super.txt</NF_StoragePath>
<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</Content>
Note: there is an issue with folder deployment as folder needs to exist to deploy a file:
<Content Include="folder\another.txt"> => will be deployed as "I:\folder\another.txt" **if and only if ** the "I:\folder" exists
<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</Content>
```
So, this is something …
=> Add Content file deployment to internal storage

vs-extension.shared/DeployProvider/DeployProvider.cs
* Fixes the spelling of `deplpoyed` to `deployed`
- No issue exists
=> Fix the spelling of deployed

VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json
=> Update msbuild task to 4.0.0-preview.5

vs-extension.shared/Utilities/ReferenceCrawler.cs
Messed up the git branch management. Same PR as #889 , now based on the main branch.
See #889
=> Add DeployToNanoDevice project property to control deployment

VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json
=> Update msbuild task to 4.0.0-preview.16

VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json
=> Update msbuild task to 4.0.0-preview.19

VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj, VisualStudio.Extension-2019/packages.lock.json, VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj, VisualStudio.Extension-2022/packages.lock.json
- Update metada processor to 4.0.0-preview.46
=> Update metada processor to 4.0.0-preview.46
